#-------------------------------------------------------------------------#
#-- Makefile for libpfdwb -- the DWB file loader			--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:33 $					--#
#-------------------------------------------------------------------------#

ifndef PFROOT
PFROOT = $(ROOT)
endif

include $(PFROOT)/usr/share/Performer/src/pfmakedefs.linux


#-- base name of library
LIBRARY	= libpfdwb

CFILES = \
	pfdwb.c \
	pfstoredwb.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules.linux
