#-------------------------------------------------------------------------#
#-- Makefile for libpfprojtex -- "projtex" pseudo-loader		--#
#-------------------------------------------------------------------------#

ifndef PFROOT
PFROOT = $(ROOT)
endif

include $(PFROOT)/usr/share/Performer/src/pfmakedefs.linux


#-- base name of library
LIBRARY	= libpfprojtex

CXXFILES = \
        pfprojtex.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules.linux
