#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfprojtex -- "projtex" pseudo-loader		--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfprojtex

CXXFILES = \
        pfprojtex.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules
