## Process this with automake to produce Makefile.in

##
## $Source: /oss/CVS/cvs/performer/src/pyper/tests/Makefile.am,v $
## $Author: flynnt $
## $Revision: 1.1 $
##

EXTRA_DIST = \
  tst2.py \
  tst3.py \
  minimal.py \
  runtest.sh

pkgdata_SCRIPTS = \
  tst2.py \
  tst3.py \
  minimal.py \
  runtest.sh

## $Log: Makefile.am,v $
## Revision 1.1  2001/05/21 21:40:00  flynnt
## Doing some cleanup and adding the pfgtk example and the python wrapper for
## Performer (pyper).
##
## Revision 1.2  2001/04/05 15:52:48  bram
## added sample
##
## Revision 1.1  2000/08/23 12:40:32  bram
## added tests
##

