#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfpfb -- the pfb file loader			--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:34 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfpfb

CFILES = \
        pfpfb.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules
