#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfct -- viewer for clip texture configuration files --#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:33 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfct

CXXFILES = \
        pfct.C

include $(PFROOT)/usr/share/Performer/src/pfmakerules
