#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfpost -- Performer example POST file loader	--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:34 $					--#
#-------------------------------------------------------------------------#

ifndef PFROOT
PFROOT = $(ROOT)
endif

include $(PFROOT)/usr/share/Performer/src/pfmakedefs.linux


#-- base name of library
LIBRARY	= libpfpost

CFILES = \
        pfpost.o


include $(PFROOT)/usr/share/Performer/src/pfmakerules.linux
