#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpflsa -- the Lightscape ASCII file loader		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:33 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpflsa

CFILES = \
        pflsa.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules
