#!smake -J 1
#-------------------------------------------------------------------------#
#-- Makefile for Performer/src/lib/libpfui				--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:35 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfui

CXXFILES = \
 	pfiCollide.C \
 	cCollide.C \
 	pfiInit.C \
 	pfiInputXform.C \
 	cInputXform.C \
 	pfiPick.C \
 	cPick.C \
 	pfiXformer.C \
 	pfiDrive.C \
 	pfiFly.C \
	pfiSpheric.C \
 	pfiTrackball.C \
 	cXformer.C

HFILES = \
 	pfiCollide.h \
 	pfiInputXform.h \
 	pfiPick.h \
	pfiSpheric.h \
	pfiXformer.h 


include $(PFROOT)/usr/share/Performer/src/pfmakerules
