/* pfosg_pfb_stubs.cpp - GENERATED by tools/harvest_pfb_api.py:
 * accept-and-ignore implementations of the Performer API surface
 * referenced by SGI's pfpfb.c but not needed by the demo databases
 * (fluxes, engines, image caches, IBR, ASD, clip textures, fonts...).
 * Real implementations live in pfosg_pfb.cpp; do not hand-edit. */
#include <Performer/pf.h>

extern "C" void pfASDAttr(pfASD* _asd, int _which, int _type, int _size, void *_attr)
{ }
extern "C" void pfASDConfig(pfASD* _asd)
{ }
extern "C" void pfASDEvalFunc(pfASD* _asd, pfASDEvalFuncType _eval)
{ }
extern "C" void pfASDEvalMethod(pfASD* _asd, int method)
{ }
extern "C" void pfASDGStates(pfASD* _asd, pfGeoState **gs, int num)
{ }
extern "C" void pfASDMaxMorphDepth(pfASD* _asd, int _m, float __morphweightconstraint)
{ }
extern "C" void pfASDMorphAttrs(pfASD* _asd, int _mc)
{ }
extern "C" void pfASDNumBaseFaces(pfASD* _asd, int num)
{ }
extern "C" void pfBboardPosFlux(pfBillboard* _bboard, pfFlux *_flux)
{ }
extern "C" void pfCBufferChanged(pfCycleBuffer* cBuf)
{ }
extern "C" void pfCalligFunc(pfLPointState* _lpstate, pfCalligFuncType _calligraphicCallback, void *_data)
{ }
extern "C" void pfClipTextureCenter(pfClipTexture* _cliptexture, int _s, int _t, int _r)
{ }
extern "C" void pfClipTextureClipSize(pfClipTexture* _cliptexture, int _clipSize)
{ }
extern "C" void pfClipTextureInvalidBorder(pfClipTexture* _cliptexture, int _nTexels)
{ }
extern "C" void pfClipTextureLODRange(pfClipTexture* _cliptexture, float _min, float _max)
{ }
extern "C" void pfClipTextureLevel(pfClipTexture* _cliptexture, int _level, pfObject* _levelObj)
{ }
extern "C" void pfClipTextureLevelPhaseMargin(pfClipTexture* _cliptexture, int level, int size)
{ }
extern "C" void pfClipTextureLevelPhaseShift(pfClipTexture* _cliptexture, int level, int phaseShiftS, int phaseShiftT, int phaseShiftR)
{ }
extern "C" void pfClipTextureNumEffectiveLevels(pfClipTexture* _cliptexture, int _levels)
{ }
extern "C" void pfClipTextureVirtualLODOffset(pfClipTexture* _cliptexture, int _offset)
{ }
extern "C" void pfClipTextureVirtualSize(pfClipTexture* _cliptexture, int _width, int _height, int _depth)
{ }
extern "C" int pfCtabColor(pfColortable* _ctab, int _index, PFVEC4 _acolor)
{ return 0; }
extern "C" void pfDCSMatType(pfDCS* _dcs, uint val)
{ }
extern "C" void pfDoubleDCSMat(pfDoubleDCS* _doubledcs, PFMATRIX4D m)
{ }
extern "C" void pfDoubleDCSMatType(pfDoubleDCS* _doubledcs, uint val)
{ }
extern "C" void pfDoubleFCSMatType(pfDoubleFCS* _doublefcs, uint val)
{ }
extern "C" void pfEngineDst(pfEngine* _engine, void *_data, ushort *_ilist, int _offset, int _stride)
{ }
extern "C" void pfEngineEvaluationRange(pfEngine* _engine, PFVEC3 _center, float _min, float _max)
{ }
extern "C" void pfEngineIterations(pfEngine* _engine, int _iterations, int _itemsPer)
{ }
extern "C" void pfEngineMask(pfEngine* _engine, uint _mask)
{ }
extern "C" void pfEngineMode(pfEngine* _engine, int _mode, int _val)
{ }
extern "C" void pfEngineSrc(pfEngine* _engine, int _index, void *_data, ushort *_ilist, int _icount, int _offset, int _stride)
{ }
extern "C" void pfEngineUserFunction(pfEngine* _engine, pfEngineFuncType _func)
{ }
extern "C" void pfFCSMatType(pfFCS* _fcs, uint val)
{ }
extern "C" void pfFluxInitData(pfFlux* _flux, void *_data)
{ }
extern "C" void pfFluxMask(pfFlux* _flux, uint _mask)
{ }
extern "C" void pfFluxMode(pfFlux* _flux, int _mode, int _val)
{ }
extern "C" void pfFluxSyncGroup(pfFlux* _flux, uint _syncGroup)
{ }
extern "C" void pfFogOffsets(pfFog* _fog, float _onset, float _opaque)
{ }
extern "C" void pfFogRamp(pfFog* _fog, int _points, float* _range, float* _density, float _bias)
{ }
extern "C" void pfFontAttr(pfFont* _font, int _which, void *attr)
{ }
extern "C" void pfFontCharGSet(pfFont* _font, int _ascii, pfGeoSet *_gset)
{ }
extern "C" void pfFontCharSpacing(pfFont* _font, int _ascii, PFVEC3 _spacing)
{ }
extern "C" void pfFontMode(pfFont* _font, int mode, int val)
{ }
extern "C" void pfFontVal(pfFont* _font, int _which, float _val)
{ }
extern "C" void pfGSetAppearance(pfGeoSet* _gset, islAppearance *appearance_)
{ }
extern "C" void pfGSetBBox(pfGeoSet* _gset, pfBox* _box, int _mode)
{ }
extern "C" void pfGSetBBoxFlux(pfGeoSet* _gset, pfFlux* _flux)
{ }
extern "C" void pfGSetDecalPlane(pfGeoSet* _gset, pfPlane *_plane)
{ }
extern "C" void pfGSetDrawBin(pfGeoSet* _gset, short bin)
{ }
extern "C" void pfGSetDrawOrder(pfGeoSet* _gset, unsigned int order)
{ }
extern "C" void pfGSetGStateIndex(pfGeoSet* _gset, int _id)
{ }
extern "C" void pfGSetHlight(pfGeoSet* _gset, pfHighlight *_hlight)
{ }
extern "C" void pfGSetMultiAttr(pfGeoSet* _gset, int _attr, int _index, int _bind, void* _alist, unsigned short* _ilist)
{ }
extern "C" void pfGStateInherit(pfGeoState* _gstate, uint64_t _mask)
{ }
extern "C" void pfGStateMultiAttr(pfGeoState* _gstate, uint64_t _attr, int _index, void* _a)
{ }
extern "C" void pfGStateMultiMode(pfGeoState* _gstate, uint64_t _attr, int _index, int _a)
{ }
extern "C" void pfGetASDAttr(pfASD* _asd, int _which, int *_type, int *_size, void **_attr)
{ }
extern "C" pfType* pfGetASDClassType(void)
{ return 0; }
extern "C" pfASDEvalFuncType pfGetASDEvalFunc(pfASD* _asd)
{ return 0; }
extern "C" int pfGetASDEvalMethod(pfASD* _asd)
{ return 0; }
extern "C" pfGeoState* pfGetASDGState(pfASD* _asd, int num)
{ return 0; }
extern "C" void pfGetASDMaxMorphDepth(pfASD* _asd, int *_m, float *__morphweightconstraint)
{ }
extern "C" int pfGetASDMorphAttrs(pfASD* _asd)
{ return 0; }
extern "C" int pfGetASDNumBaseFaces(pfASD* _asd)
{ return 0; }
extern "C" int pfGetASDNumGStates(pfASD* _asd)
{ return 0; }
extern "C" void pfGetBboardAxis(pfBillboard* _bboard, PFVEC3 axis)
{ }
extern "C" int pfGetBboardMode(pfBillboard* _bboard, int _mode)
{ return 0; }
extern "C" void pfGetBboardPos(pfBillboard* _bboard, int i, PFVEC3 pos)
{ }
extern "C" pfFlux* pfGetBboardPosFlux(pfBillboard* _bboard)
{ return 0; }
extern "C" pfCycleBuffer* pfGetCBuffer(void *data)
{ return 0; }
extern "C" pfType* pfGetCBufferClassType(void)
{ return 0; }
extern "C" void pfGetCalligFunc(pfLPointState* _lpstate, pfCalligFuncType *_calligraphicCallback, void **_data)
{ }
extern "C" void pfGetClipTextureCenter(pfClipTexture* _cliptexture, int *_s, int *_t, int *_r)
{ }
extern "C" pfType* pfGetClipTextureClassType(void)
{ return 0; }
extern "C" int pfGetClipTextureClipSize(pfClipTexture* _cliptexture)
{ return 0; }
extern "C" uint pfGetClipTextureDTRMode(pfClipTexture* _cliptexture)
{ return 0; }
extern "C" int pfGetClipTextureInvalidBorder(pfClipTexture* _cliptexture)
{ return 0; }
extern "C" void pfGetClipTextureLODRange(pfClipTexture* _cliptexture, float *_min, float *_max)
{ }
extern "C" pfObject* pfGetClipTextureLevel(pfClipTexture* _cliptexture, int _level)
{ return 0; }
extern "C" int pfGetClipTextureLevelPhaseMargin(pfClipTexture* _cliptexture, int level)
{ return 0; }
extern "C" void pfGetClipTextureLevelPhaseShift(pfClipTexture* _cliptexture, int level, int *phaseShiftS, int *phaseShiftT, int *phaseShiftR)
{ }
extern "C" pfClipTexture* pfGetClipTextureMaster(const pfClipTexture* _cliptexture)
{ return 0; }
extern "C" int pfGetClipTextureNumEffectiveLevels(pfClipTexture* _cliptexture)
{ return 0; }
extern "C" int pfGetClipTextureVirtualLODOffset(pfClipTexture* _cliptexture)
{ return 0; }
extern "C" void pfGetClipTextureVirtualSize(pfClipTexture* _cliptexture, int *_width, int *_height, int *_depth)
{ }
extern "C" pfType* pfGetCtabClassType(void)
{ return 0; }
extern "C" pfVec4* pfGetCtabColors(const pfColortable* _ctab)
{ return 0; }
extern "C" int pfGetCtabSize(const pfColortable* _ctab)
{ return 0; }
extern "C" void* pfGetCurCBufferData(const pfCycleBuffer* cBuf)
{ return 0; }
extern "C" pfType* pfGetDCSClassType(void)
{ return 0; }
extern "C" uint pfGetDCSMatType(const pfDCS* _dcs)
{ return 0; }
extern "C" void pfGetDirDataDirections(pfDirData* _dirdata, int *num, pfVec3 **directions)
{ }
extern "C" int pfGetDirDataNumGroups(pfDirData* _dirdata, int *viewsPerGroup)
{ return 0; }
extern "C" pfType* pfGetDoubleDCSClassType(void)
{ return 0; }
extern "C" void pfGetDoubleDCSMat(pfDoubleDCS* _doubledcs, PFMATRIX4D m)
{ }
extern "C" uint pfGetDoubleDCSMatType(const pfDoubleDCS* _doubledcs)
{ return 0; }
extern "C" pfType* pfGetDoubleFCSClassType(void)
{ return 0; }
extern "C" pfFlux* pfGetDoubleFCSFlux(pfDoubleFCS* _doublefcs)
{ return 0; }
extern "C" uint pfGetDoubleFCSMatType(const pfDoubleFCS* _doublefcs)
{ return 0; }
extern "C" pfType* pfGetDoubleSCSClassType(void)
{ return 0; }
extern "C" void pfGetDoubleSCSMat(pfDoubleSCS* _doublescs, PFMATRIX4D m)
{ }
extern "C" void pfGetEngineDst(const pfEngine* _engine, void **_data, ushort **_ilist, int *_offset, int *_stride)
{ }
extern "C" void pfGetEngineEvaluationRange(const pfEngine* _engine, PFVEC3 _center, float *_min, float *_max)
{ }
extern "C" int pfGetEngineFunction(const pfEngine* _engine)
{ return 0; }
extern "C" void pfGetEngineIterations(const pfEngine* _engine, int *_iterations, int *_itemsPer)
{ }
extern "C" uint pfGetEngineMask(const pfEngine* _engine)
{ return 0; }
extern "C" int pfGetEngineMode(const pfEngine* _engine, int _mode)
{ return 0; }
extern "C" int pfGetEngineNumSrcs(const pfEngine* _engine)
{ return 0; }
extern "C" void pfGetEngineSrc(const pfEngine* _engine, int _index, void **_data, ushort **_ilist, int *_icount, int *_offset, int *_stride)
{ }
extern "C" pfEngineFuncType pfGetEngineUserFunction(const pfEngine* _engine)
{ return 0; }
extern "C" pfType* pfGetFCSClassType(void)
{ return 0; }
extern "C" pfFlux* pfGetFCSFlux(pfFCS* _fcs)
{ return 0; }
extern "C" uint pfGetFCSMatType(const pfFCS* _fcs)
{ return 0; }
extern "C" pfFlux* pfGetFlux(void *_data)
{ return 0; }
extern "C" pfType* pfGetFluxClassType(void)
{ return 0; }
extern "C" pfEngine* pfGetFluxClientEngine(const pfFlux* _flux, int _index)
{ return 0; }
extern "C" void* pfGetFluxCurData(pfFlux* _flux)
{ return 0; }
extern "C" size_t pfGetFluxDataSize(const pfFlux* _flux)
{ return 0; }
extern "C" uint pfGetFluxMask(const pfFlux* _flux)
{ return 0; }
extern "C" int pfGetFluxMode(const pfFlux* _flux, int _mode)
{ return 0; }
extern "C" int pfGetFluxNamedSyncGroup(const char *_name)
{ return 0; }
extern "C" int pfGetFluxNumBuffers(const pfFlux* _flux, int _type)
{ return 0; }
extern "C" int pfGetFluxNumClientEngines(const pfFlux* _flux)
{ return 0; }
extern "C" int pfGetFluxNumSrcEngines(const pfFlux* _flux)
{ return 0; }
extern "C" pfEngine* pfGetFluxSrcEngine(const pfFlux* _flux, int _index)
{ return 0; }
extern "C" uint pfGetFluxSyncGroup(const pfFlux* _flux)
{ return 0; }
extern "C" const char* pfGetFluxSyncGroupName(uint _syncGroup)
{ return 0; }
extern "C" pfType* pfGetFogClassType(void)
{ return 0; }
extern "C" void pfGetFogColor(const pfFog* _fog, float* _r, float* _g, float* _b)
{ }
extern "C" void pfGetFogOffsets(const pfFog* _fog, float *_onset, float *_opaque)
{ }
extern "C" void pfGetFogRamp(const pfFog* _fog, int* _points, float* _range, float* _density, float* _bias)
{ }
extern "C" void pfGetFogRange(const pfFog* _fog, float* _onset, float* _opaque)
{ }
extern "C" int pfGetFogType(const pfFog* _fog)
{ return 0; }
extern "C" void* pfGetFontAttr(pfFont* _font, int _which)
{ return 0; }
extern "C" pfGeoSet* pfGetFontCharGSet(pfFont* _font, int _ascii)
{ return 0; }
extern "C" const pfVec3* pfGetFontCharSpacing(pfFont* _font, int _ascii)
{ return 0; }
extern "C" pfType* pfGetFontClassType(void)
{ return 0; }
extern "C" int pfGetFontMode(pfFont* _font, int mode)
{ return 0; }
extern "C" float pfGetFontVal(pfFont* _font, int _which)
{ return 0.0f; }
extern "C" pfFlux* pfGetFrameTimeFlux(void)
{ return 0; }
extern "C" islAppearance* pfGetGSetAppearance(const pfGeoSet* _gset)
{ return 0; }
extern "C" int pfGetGSetAttrRange(const pfGeoSet* _gset, int _attr, int *_min, int *_max)
{ return 0; }
extern "C" int pfGetGSetBBox(pfGeoSet* _gset, pfBox* _box)
{ return 0; }
extern "C" pfFlux* pfGetGSetBBoxFlux(pfGeoSet* _gset)
{ return 0; }
extern "C" pfPlane* pfGetGSetDecalPlane(const pfGeoSet* _gset)
{ return 0; }
extern "C" int pfGetGSetDrawBin(const pfGeoSet* _gset)
{ return 0; }
extern "C" unsigned int pfGetGSetDrawOrder(const pfGeoSet* _gset)
{ return 0; }
extern "C" int pfGetGSetGStateIndex(const pfGeoSet* _gset)
{ return 0; }
extern "C" pfHighlight* pfGetGSetHlight(const pfGeoSet* _gset)
{ return 0; }
extern "C" int pfGetGSetMultiAttrBind(const pfGeoSet* _gset, int _attr, int _index)
{ return 0; }
extern "C" void pfGetGSetMultiAttrLists(const pfGeoSet* _gset, int _attr, int _index, void** _alist, unsigned short** _ilist)
{ }
extern "C" int pfGetGSetMultiAttrRange(const pfGeoSet* _gset, int _attr, int _index, int *_min, int *_max)
{ return 0; }
extern "C" void* pfGetGStateAttr(const pfGeoState* _gstate, uint64_t _attr)
{ return 0; }
extern "C" pfType* pfGetGStateClassType(void)
{ return 0; }
extern "C" uint64_t pfGetGStateInherit(const pfGeoState* _gstate)
{ return 0; }
extern "C" int pfGetGStateMode(const pfGeoState* _gstate, uint64_t _attr)
{ return 0; }
extern "C" void* pfGetGStateMultiAttr(const pfGeoState* _gstate, uint64_t _attr, int _index)
{ return 0; }
extern "C" int pfGetGStateMultiMode(const pfGeoState* _gstate, uint64_t _attr, int _index)
{ return 0; }
extern "C" float pfGetGStateVal(const pfGeoState* _gstate, uint64_t _attr)
{ return 0.0f; }
extern "C" pfQueue* pfGetGlobalReadQueue(void)
{ return 0; }
extern "C" float pfGetHlightAlpha(const pfHighlight* _hlight)
{ return 0.0f; }
extern "C" pfType* pfGetHlightClassType(void)
{ return 0; }
extern "C" void pfGetHlightColor(const pfHighlight* _hlight, unsigned int _which, float *_r, float *_g, float *_b)
{ }
extern "C" void pfGetHlightFillPat(const pfHighlight* _hlight, int _which, unsigned int *_pat)
{ }
extern "C" pfGeoState* pfGetHlightGState(const pfHighlight* _hlight)
{ return 0; }
extern "C" int pfGetHlightGStateIndex(const pfHighlight* _hlight)
{ return 0; }
extern "C" unsigned short pfGetHlightLinePat(const pfHighlight* _hlight, int _which)
{ return 0; }
extern "C" float pfGetHlightLineWidth(const pfHighlight* _hlight)
{ return 0.0f; }
extern "C" unsigned int pfGetHlightMode(const pfHighlight* _hlight)
{ return 0; }
extern "C" void pfGetHlightNormalLength(const pfHighlight* _hlight, float *_len, float *_bboxScale)
{ }
extern "C" float pfGetHlightPntSize(const pfHighlight* _hlight)
{ return 0.0f; }
extern "C" pfTexEnv* pfGetHlightTEnv(const pfHighlight* _hlight)
{ return 0; }
extern "C" pfTexGen* pfGetHlightTGen(const pfHighlight* _hlight)
{ return 0; }
extern "C" pfTexture* pfGetHlightTex(const pfHighlight* _hlight)
{ return 0; }
extern "C" void pfGetIBRnodeAngles(pfIBRnode* _ibrnode, int i, float *horAngle, float *verAngle)
{ }
extern "C" pfType* pfGetIBRnodeClassType(void)
{ return 0; }
extern "C" int pfGetIBRnodeFlags(const pfIBRnode* _ibrnode, int which)
{ return 0; }
extern "C" pfIBRtexture* pfGetIBRnodeIBRtexture(pfIBRnode* _ibrnode)
{ return 0; }
extern "C" int pfGetIBRnodeNumAngles(pfIBRnode* _ibrnode)
{ return 0; }
extern "C" pfVec2*** pfGetIBRnodeProxyTexCoords(pfIBRnode* _ibrnode)
{ return 0; }
extern "C" pfDirData* pfGetIBRtextureDirData(pfIBRtexture* _ibrtexture)
{ return 0; }
extern "C" float pfGetIBRtextureDirection(const pfIBRtexture* _ibrtexture)
{ return 0.0f; }
extern "C" int pfGetIBRtextureFlags(const pfIBRtexture* _ibrtexture, int which)
{ return 0; }
extern "C" void pfGetIBRtextureIBRTextures(pfIBRtexture* _ibrtexture, pfTexture ***textures, int *numTex)
{ }
extern "C" void pfGetIBRtextureIBRdirections(pfIBRtexture* _ibrtexture, pfVec3 **directions, int *numDirs)
{ }
extern "C" pfType* pfGetImageCacheClassType(void)
{ return 0; }
extern "C" const char* pfGetImageCacheFileStreamServer(pfImageCache* _imagecache, int _dim, int _which)
{ return 0; }
extern "C" void pfGetImageCacheImageSize(pfImageCache* _imagecache, int *_sizeS, int *_sizeT, int *_sizeR)
{ }
extern "C" pfImageCache* pfGetImageCacheMaster(const pfImageCache* _imagecache)
{ return 0; }
extern "C" void pfGetImageCacheMemRegionOrg(pfImageCache* _imagecache, int *_orgTileS, int *_orgTileT, int *_orgTileR)
{ }
extern "C" void pfGetImageCacheMemRegionSize(pfImageCache* _imagecache, int *_sizeS, int *_sizeT, int *_sizeR)
{ }
extern "C" int pfGetImageCacheMode(pfImageCache* _imagecache, int _mode)
{ return 0; }
extern "C" const char* pfGetImageCacheName(pfImageCache* _imagecache)
{ return 0; }
extern "C" int pfGetImageCacheNumStreamServers(const pfImageCache* _imagecache, int _dim)
{ return 0; }
extern "C" pfImageTile* pfGetImageCacheProtoTile(pfImageCache* _imagecache)
{ return 0; }
extern "C" pfImageCacheReadQueueFuncType pfGetImageCacheReadQueueFunc(pfImageCache* _imagecache)
{ return 0; }
extern "C" pfQueue* pfGetImageCacheStreamServerQueue(pfImageCache* _imagecache, int _dim, int _which)
{ return 0; }
extern "C" void pfGetImageCacheTex(pfImageCache* _imagecache, void **_dst, int *_lvl, int *_type)
{ }
extern "C" void pfGetImageCacheTexRegionOrg(pfImageCache* _imagecache, int *_originS, int *_originT, int *_originR)
{ }
extern "C" void pfGetImageCacheTexRegionSize(pfImageCache* _imagecache, int *_sizeS, int *_sizeT, int *_sizeR)
{ }
extern "C" void pfGetImageCacheTexSize(pfImageCache* _imagecache, int *_s, int *_t, int *_r)
{ }
extern "C" void pfGetImageCacheTileFileNameFormat(pfImageCache* _imagecache, const char **_fmtString, int *_nArgs, const int **_argList)
{ }
extern "C" pfTileFileNameFuncType pfGetImageCacheTileFileNameFunc(pfImageCache* _imagecache)
{ return 0; }
extern "C" pfImageTile* pfGetImageTileDefaultTile(pfImageTile* _imagetile)
{ return 0; }
extern "C" int pfGetImageTileDefaultTileMode(pfImageTile* _imagetile)
{ return 0; }
extern "C" int pfGetImageTileFileImageFormat(pfImageTile* _imagetile)
{ return 0; }
extern "C" int pfGetImageTileFileImageType(pfImageTile* _imagetile)
{ return 0; }
extern "C" const char* pfGetImageTileFileName(pfImageTile* _imagetile)
{ return 0; }
extern "C" void pfGetImageTileFileTile(pfImageTile* _imagetile, int *_tileS, int *_tileT, int *_tileR)
{ }
extern "C" int pfGetImageTileHeaderOffset(pfImageTile* _imagetile)
{ return 0; }
extern "C" int pfGetImageTileMemImageFormat(pfImageTile* _imagetile)
{ return 0; }
extern "C" int pfGetImageTileMemImageType(pfImageTile* _imagetile)
{ return 0; }
extern "C" void pfGetImageTileMemInfo(pfImageTile* _imagetile, int *_psize, int *_lock)
{ }
extern "C" const char* pfGetImageTileName(pfImageTile* _imagetile)
{ return 0; }
extern "C" void pfGetImageTileNumFileTiles(pfImageTile* _imagetile, int *_nTilesS, int *_nTilesT, int *_nTilesR)
{ }
extern "C" void pfGetImageTileOrigin(pfImageTile* _imagetile, int *_s, int *_t, int *_r)
{ }
extern "C" int pfGetImageTilePriority(pfImageTile* _imagetile)
{ return 0; }
extern "C" pfReadImageTileFuncType pfGetImageTileReadFunc(pfImageTile* _imagetile)
{ return 0; }
extern "C" pfQueue* pfGetImageTileReadQueue(pfImageTile* _imagetile)
{ return 0; }
extern "C" void pfGetImageTileSize(pfImageTile* _imagetile, int *_w, int *_h,int *_d)
{ }
extern "C" void pfGetLModelAmbient(const pfLightModel* _lmodel, float* _r, float* _g, float* _b)
{ }
extern "C" void pfGetLModelAtten(const pfLightModel* _lmodel, float* _a0, float* _a1, float* _a2)
{ }
extern "C" pfType* pfGetLModelClassType(void)
{ return 0; }
extern "C" int pfGetLModelLocal(const pfLightModel* _lmodel)
{ return 0; }
extern "C" int pfGetLModelTwoSide(const pfLightModel* _lmodel)
{ return 0; }
extern "C" pfType* pfGetLODClassType(void)
{ return 0; }
extern "C" pfLODState* pfGetLODLODState(const pfLOD* _lod)
{ return 0; }
extern "C" int pfGetLODLODStateIndex(const pfLOD* _lod)
{ return 0; }
extern "C" float pfGetLODStateAttr(pfLODState* _lodstate, int attr)
{ return 0.0f; }
extern "C" pfType* pfGetLODStateClassType(void)
{ return 0; }
extern "C" const char* pfGetLODStateName(const pfLODState* _lodstate)
{ return 0; }
extern "C" float pfGetLODTransition(const pfLOD* _lod, int index)
{ return 0.0f; }
extern "C" void pfGetLPStateBackColor(pfLPointState* _lpstate, float *r, float *g, float *b, float *a)
{ }
extern "C" pfType* pfGetLPStateClassType(void)
{ return 0; }
extern "C" int pfGetLPStateMode(const pfLPointState* _lpstate, int _mode)
{ return 0; }
extern "C" void pfGetLPStateShape(const pfLPointState* _lpstate, float *_horiz, float *_vert, float *_roll, float *_falloff, float *_ambient)
{ }
extern "C" float pfGetLPStateVal(const pfLPointState* _lpstate, int _attr)
{ return 0.0f; }
extern "C" pfType* pfGetLPointClassType(void)
{ return 0; }
extern "C" pfGeoSet* pfGetLPointGSet(const pfLightPoint* _lpoint)
{ return 0; }
extern "C" void pfGetLSourceAtten(pfLightSource* _lsource, float* _a0, float* _a1, float* _a2)
{ }
extern "C" void* pfGetLSourceAttr(const pfLightSource* _lsource, int attr)
{ return 0; }
extern "C" pfType* pfGetLSourceClassType(void)
{ return 0; }
extern "C" void pfGetLSourceColor(pfLightSource* _lsource, int _which, float* _r, float* _g, float* _b)
{ }
extern "C" int pfGetLSourceMode(const pfLightSource* _lsource, int mode)
{ return 0; }
extern "C" void pfGetLSourcePos(pfLightSource* _lsource, float* _x, float* _y, float* _z, float* _w)
{ }
extern "C" float pfGetLSourceVal(const pfLightSource* _lsource, int mode)
{ return 0.0f; }
extern "C" int pfGetLayerMode(const pfLayer* _layer)
{ return 0; }
extern "C" void pfGetLightAtten(const pfLight* _light, float* _a0, float* _a1, float* _a2)
{ }
extern "C" pfType* pfGetLightClassType(void)
{ return 0; }
extern "C" void pfGetLightColor(const pfLight* _light, int _which, float* _r, float* _g, float* _b)
{ }
extern "C" pfType* pfGetMemoryClassType(void)
{ return 0; }
extern "C" pfType* pfGetMorphClassType(void)
{ return 0; }
extern "C" void* pfGetMorphDst(const pfMorph* _morph, int index)
{ return 0; }
extern "C" int pfGetMorphNumAttrs(const pfMorph* _morph)
{ return 0; }
extern "C" int pfGetMorphNumSrcs(const pfMorph* _morph, int index)
{ return 0; }
extern "C" int pfGetMorphSrc(const pfMorph* _morph, int index, int src, float **alist, ushort **ilist, int *n)
{ return 0; }
extern "C" int pfGetMorphWeights(const pfMorph* _morph, int index, float *weights)
{ return 0; }
extern "C" pfType* pfGetMtlClassType(void)
{ return 0; }
extern "C" void pfGetMtlColor(pfMaterial* _mtl, int _acolor, float* _r, float* _g, float* _b)
{ }
extern "C" int pfGetMtlColorMode(pfMaterial* _mtl, int _side)
{ return 0; }
extern "C" int pfGetMtlSide(pfMaterial* _mtl)
{ return 0; }
extern "C" int pfGetNamedUserDataSlot(const char *_name)
{ return 0; }
extern "C" int pfGetNumNamedUserDataSlots(void)
{ return 0; }
extern "C" int pfGetNumStrings(const pfText* _text)
{ return 0; }
extern "C" int pfGetNumUserData(pfObject* _obj)
{ return 0; }
extern "C" pfType* pfGetObjectClassType(void)
{ return 0; }
extern "C" void* pfGetPartAttr(pfPartition* _part, int which)
{ return 0; }
extern "C" pfType* pfGetPartClassType(void)
{ return 0; }
extern "C" float pfGetPartVal(pfPartition* _part, int which)
{ return 0.0f; }
extern "C" int pfGetQueueArrayLen(pfQueue* _queue)
{ return 0; }
extern "C" void pfGetRasterFunc(pfLPointState* _lpstate, pfRasterFuncType *_rasterCallback, void **_data)
{ }
extern "C" pfType* pfGetSceneClassType(void)
{ return 0; }
extern "C" pfGeoState* pfGetSceneGState(const pfScene* _scene)
{ return 0; }
extern "C" int pfGetSceneGStateIndex(const pfScene* _scene)
{ return 0; }
extern "C" void pfGetSeqDuration(const pfSequence* _seq, float *sp, int *nRep)
{ }
extern "C" void pfGetSeqInterval(const pfSequence* _seq, int *imode, int *beg, int *e)
{ }
extern "C" int pfGetSeqMode(const pfSequence* _seq)
{ return 0; }
extern "C" double pfGetSeqTime(const pfSequence* _seq, int index)
{ return 0.0f; }
extern "C" size_t pfGetSize(void *data)
{ return 0; }
extern "C" void pfGetSpotLSourceCone(pfLightSource* _lsource, float* _f1, float* _f2)
{ }
extern "C" void pfGetSpotLSourceDir(pfLightSource* _lsource, float* _x, float* _y, float* _z)
{ }
extern "C" void pfGetSpotLightCone(const pfLight* _light, float* _f1, float* _f2)
{ }
extern "C" void pfGetSpotLightDir(const pfLight* _light, float* _x, float* _y, float* _z)
{ }
extern "C" pfString* pfGetString(const pfText* _text, int i)
{ return 0; }
extern "C" pfType* pfGetStringClassType(void)
{ return 0; }
extern "C" void pfGetStringColor(const pfString* _string, float *r, float *g, float *b, float *a)
{ }
extern "C" pfFont* pfGetStringFont(const pfString* _string)
{ return 0; }
extern "C" pfGeoState* pfGetStringGState(const pfString* _string)
{ return 0; }
extern "C" uint pfGetStringIsectMask(const pfString* _string)
{ return 0; }
extern "C" void pfGetStringMat(const pfString* _string, PFMATRIX _mat)
{ }
extern "C" int pfGetStringMode(const pfString* _string, int _mode)
{ return 0; }
extern "C" void pfGetStringSpacingScale(const pfString* _string, float *sx, float *sy, float *sz)
{ }
extern "C" const char* pfGetStringString(const pfString* _string)
{ return 0; }
extern "C" void pfGetTEnvBlendColor(pfTexEnv* _tenv, float* _r, float* _g, float* _b, float* _a)
{ }
extern "C" pfType* pfGetTEnvClassType(void)
{ return 0; }
extern "C" int pfGetTEnvComponent(const pfTexEnv* _tenv)
{ return 0; }
extern "C" int pfGetTEnvMode(const pfTexEnv* _tenv)
{ return 0; }
extern "C" pfType* pfGetTGenClassType(void)
{ return 0; }
extern "C" int pfGetTGenMode(const pfTexGen* _tgen, int _texCoord)
{ return 0; }
extern "C" void pfGetTGenPlane(pfTexGen* _tgen, int _texCoord, float* _x, float* _y, float* _z, float* _d)
{ }
extern "C" void pfGetTLODBias(pfTexLOD* _tlod, float *_biasS, float *_biasT, float *_biasR)
{ }
extern "C" void pfGetTLODRange(pfTexLOD* _tlod, float *_min, float *_max)
{ }
extern "C" int pfGetTexAnisotropy(const pfTexture* _tex)
{ return 0; }
extern "C" void pfGetTexBorderColor(pfTexture* _tex, pfVec4 *_clr)
{ }
extern "C" int pfGetTexBorderType(pfTexture* _tex)
{ return 0; }
extern "C" pfType* pfGetTexClassType(void)
{ return 0; }
extern "C" void pfGetTexDetail(const pfTexture* _tex, int *_l, pfTexture **_detail)
{ }
extern "C" pfTexture* pfGetTexDetailTex(const pfTexture* _tex)
{ return 0; }
extern "C" float pfGetTexFrame(const pfTexture* _tex)
{ return 0.0f; }
extern "C" pfTexture* pfGetTexLevel(pfTexture* _tex, int _level)
{ return 0; }
extern "C" pfList* pfGetTexList(const pfTexture* _tex)
{ return 0; }
extern "C" unsigned int* pfGetTexLoadImage(const pfTexture* _tex)
{ return 0; }
extern "C" int pfGetTexLoadMode(const pfTexture* _tex, int _mode)
{ return 0; }
extern "C" void pfGetTexLoadOrigin(pfTexture* _tex, int _which, int *_xo, int *_yo)
{ }
extern "C" void pfGetTexLoadSize(const pfTexture* _tex, int *_xs, int *_ys)
{ }
extern "C" const char* pfGetTexName(const pfTexture* _tex)
{ return 0; }
extern "C" void pfGetTexSpline(const pfTexture* _tex, int _type, pfVec2 *_pts, float *_clamp)
{ }
extern "C" pfType* pfGetTextClassType(void)
{ return 0; }
extern "C" pfType* pfGetType(const void *data)
{ return 0; }
extern "C" void* pfGetUserData(pfObject* _obj)
{ return 0; }
extern "C" void* pfGetUserDataSlot(pfObject* _obj, int _slot)
{ return 0; }
extern "C" const char* pfGetUserDataSlotName(int _slot)
{ return 0; }
extern "C" void pfHlightAlpha(pfHighlight* _hlight, float _a)
{ }
extern "C" void pfHlightFillPat(pfHighlight* _hlight, int _which, unsigned int *fillPat )
{ }
extern "C" void pfHlightGState(pfHighlight* _hlight, pfGeoState *_gstate)
{ }
extern "C" void pfHlightGStateIndex(pfHighlight* _hlight, int _id)
{ }
extern "C" void pfHlightLinePat(pfHighlight* _hlight, int _which, unsigned short _pat)
{ }
extern "C" void pfHlightNormalLength(pfHighlight* _hlight, float _len, float _bboxScale)
{ }
extern "C" void pfHlightTEnv(pfHighlight* _hlight, pfTexEnv *_tev)
{ }
extern "C" void pfHlightTGen(pfHighlight* _hlight, pfTexGen *_tgen)
{ }
extern "C" void pfHlightTex(pfHighlight* _hlight, pfTexture *_tex)
{ }
extern "C" void pfIBRnodeAngles(pfIBRnode* _ibrnode, int i, float horAngle, float verAngle)
{ }
extern "C" void pfIBRnodeFlags(pfIBRnode* _ibrnode, int which, int value)
{ }
extern "C" void pfIBRnodeIBRtexture(pfIBRnode* _ibrnode, pfIBRtexture *tex)
{ }
extern "C" void pfIBRnodeProxyTexCoords(pfIBRnode* _ibrnode, pfVec2 ***texCoords)
{ }
extern "C" void pfIBRtextureDirection(pfIBRtexture* _ibrtexture, float dir)
{ }
extern "C" void pfIBRtextureFlags(pfIBRtexture* _ibrtexture, int which, int value)
{ }
extern "C" void pfIBRtextureIBRTexture(pfIBRtexture* _ibrtexture, pfTexture **_textures, int _numTex)
{ }
extern "C" void pfIBRtextureIBRdirections(pfIBRtexture* _ibrtexture, pfVec3 *directions, int numDirs)
{ }
extern "C" void pfImageCacheFileStreamServer(pfImageCache* _imagecache, int _dim, int _which, const char *_device)
{ }
extern "C" void pfImageCacheImageSize(pfImageCache* _imagecache, int _sizeS, int _sizeT, int _sizeR)
{ }
extern "C" void pfImageCacheMaster(pfImageCache* _imagecache, pfImageCache *_master)
{ }
extern "C" void pfImageCacheMemRegionOrg(pfImageCache* _imagecache, int _tileS, int _tileT, int _tileR)
{ }
extern "C" void pfImageCacheMemRegionSize(pfImageCache* _imagecache, int _tileS, int _tileT, int _tileR)
{ }
extern "C" void pfImageCacheMode(pfImageCache* _imagecache, int _mode, int _val)
{ }
extern "C" void pfImageCacheName(pfImageCache* _imagecache, const char *_name)
{ }
extern "C" void pfImageCacheProtoTile(pfImageCache* _imagecache, pfImageTile *tile)
{ }
extern "C" void pfImageCacheReadQueueFunc(pfImageCache* _imagecache, pfImageCacheReadQueueFuncType _func)
{ }
extern "C" void pfImageCacheStreamServerQueue(pfImageCache* _imagecache, int _dim, int _which, pfQueue *_q)
{ }
extern "C" void pfImageCacheTex(pfImageCache* _imagecache, void *_dst, int _lvl, int _type)
{ }
extern "C" void pfImageCacheTexRegionOrg(pfImageCache* _imagecache, int _originS, int _originT, int _originR)
{ }
extern "C" void pfImageCacheTexRegionSize(pfImageCache* _imagecache, int _sizeS, int _sizeT, int _sizeR)
{ }
extern "C" void pfImageCacheTexSize(pfImageCache* _imagecache, int _s, int _t, int _r)
{ }
extern "C" void pfImageCacheTileFileNameFormat(pfImageCache* _imagecache, const char *_fmtString, int _nArgs, int *_argList)
{ }
extern "C" void pfImageCacheTileFileNameFunc(pfImageCache* _imagecache, pfTileFileNameFuncType _func)
{ }
extern "C" void pfImageTileDefaultTile(pfImageTile* _imagetile, pfImageTile *_default)
{ }
extern "C" void pfImageTileDefaultTileMode(pfImageTile* _imagetile, int _useDefault)
{ }
extern "C" void pfImageTileFileImageFormat(pfImageTile* _imagetile, int _fileFmt)
{ }
extern "C" void pfImageTileFileImageType(pfImageTile* _imagetile, int _fileType)
{ }
extern "C" void pfImageTileFileName(pfImageTile* _imagetile, const char *_fname)
{ }
extern "C" void pfImageTileFileTile(pfImageTile* _imagetile, int _tileS, int _tileT, int _tileR)
{ }
extern "C" void pfImageTileHeaderOffset(pfImageTile* _imagetile, int hdr)
{ }
extern "C" void pfImageTileMemImageFormat(pfImageTile* _imagetile, int _format)
{ }
extern "C" void pfImageTileMemImageType(pfImageTile* _imagetile, int _type)
{ }
extern "C" void pfImageTileMemInfo(pfImageTile* _imagetile, int _psize, int _lock)
{ }
extern "C" void pfImageTileName(pfImageTile* _imagetile, const char *_fname)
{ }
extern "C" void pfImageTileNumFileTiles(pfImageTile* _imagetile, int _nTilesS, int _nTilesT, int _nTilesR)
{ }
extern "C" void pfImageTileOrigin(pfImageTile* _imagetile, int _s, int _t, int _r)
{ }
extern "C" void pfImageTilePriority(pfImageTile* _imagetile, int priority)
{ }
extern "C" void pfImageTileReadFunc(pfImageTile* _imagetile, pfReadImageTileFuncType _func)
{ }
extern "C" void pfImageTileReadQueue(pfImageTile* _imagetile, pfQueue *q)
{ }
extern "C" void pfImageTileSize(pfImageTile* _imagetile, int _w, int _h, int _d)
{ }
extern "C" int pfIsConfiged(void)
{ return 0; }
extern "C" int pfIsDerivedFrom(pfType* _type, pfType *ancestor)
{ return 0; }
extern "C" int pfIsLSourceOn(pfLightSource* _lsource)
{ return 0; }
extern "C" int pfIsLightOn(pfLight* _light)
{ return 0; }
extern "C" void pfLModelAtten(pfLightModel* _lmodel, float _a0, float _a1, float _a2)
{ }
extern "C" void pfLODLODState(pfLOD* _lod, pfLODState *ls)
{ }
extern "C" void pfLODLODStateIndex(pfLOD* _lod, int index)
{ }
extern "C" void pfLODStateAttr(pfLODState* _lodstate, int attr, float val)
{ }
extern "C" int pfLODStateName(pfLODState* _lodstate, const char *name)
{ return 0; }
extern "C" void pfLODTransition(pfLOD* _lod, int index, float delta)
{ }
extern "C" void pfLPStateBackColor(pfLPointState* _lpstate, float r, float g, float b, float a)
{ }
/* pfLPStateMode/pfLPStateVal/pfNewLPState are real (pfosg_pfb.cpp) */
extern "C" void pfLPStateShape(pfLPointState* _lpstate, float _horiz, float _vert, float _roll, float _falloff, float _ambient)
{ }
extern "C" void pfLSourceAtten(pfLightSource* _lsource, float _a0, float _a1, float _a2)
{ }
extern "C" void pfLSourceAttr(pfLightSource* _lsource, int attr, void *obj)
{ }
extern "C" void pfLSourceMode(pfLightSource* _lsource, int mode, int val)
{ }
extern "C" void pfLSourceOff(pfLightSource* _lsource)
{ }
extern "C" void pfLSourceOn(pfLightSource* _lsource)
{ }
extern "C" void pfLSourceVal(pfLightSource* _lsource, int mode, float val)
{ }
extern "C" int pfMorphAttr(pfMorph* _morph, int index, int attr, int nelts, void *dst, int nsrcs, float *alist[], ushort *ilist[], int n[])
{ return 0; }
extern "C" int pfMorphWeights(pfMorph* _morph, int index, float *weights)
{ return 0; }
extern "C" pfASD* pfNewASD(void)
{ return 0; }
extern "C" pfCycleBuffer* pfNewCBuffer(size_t nbytes, void *arena)
{ return 0; }
extern "C" pfClipTexture* pfNewClipTexture(void *arena)
{ return 0; }
extern "C" pfColortable* pfNewCtab(int _size, void *arena)
{ return 0; }
extern "C" pfDoubleDCS* pfNewDoubleDCS(void)
{ return 0; }
extern "C" pfDoubleFCS* pfNewDoubleFCS(pfFlux *_flux)
{ return 0; }
extern "C" pfDoubleSCS* pfNewDoubleSCS(PFMATRIX4D m)
{ return 0; }
extern "C" pfEngine* pfNewEngine(int _function, void *arena)
{ return 0; }
extern "C" pfFCS* pfNewFCS(pfFlux *_flux)
{ return 0; }
extern "C" pfFlux* pfNewFlux(size_t nbytes, int _numBuffers, void *arena)
{ return 0; }
extern "C" pfFont* pfNewFont(void *arena)
{ return 0; }
extern "C" pfIBRnode* pfNewIBRnode(void)
{ return 0; }
extern "C" pfIBRtexture* pfNewIBRtexture(void *arena)
{ return 0; }
extern "C" pfImageCache* pfNewImageCache(void *arena)
{ return 0; }
extern "C" pfImageTile* pfNewImageTile(void *arena)
{ return 0; }
extern "C" pfLODState* pfNewLODState(void)
{ return 0; }
/* pfNewLPState is real (pfosg_pfb.cpp) */
extern "C" pfMorph* pfNewMorph(void)
{ return 0; }
extern "C" pfQueue* pfNewQueue(int _eltSize, int _nElts, void *arena)
{ return 0; }
extern "C" pfTexGen* pfNewTGen(void *arena)
{ return 0; }
extern "C" pfTexLOD* pfNewTLOD(void *arena)
{ return 0; }
extern "C" void pfRasterFunc(pfLPointState* _lpstate, pfRasterFuncType _rasterCallback, void *_data)
{ }
extern "C" int pfSaveTexFile(pfTexture* _tex, const char* _fname)
{ return 0; }
extern "C" void pfSceneGStateIndex(pfScene* _scene, int gs)
{ }
extern "C" void pfSpotLSourceCone(pfLightSource* _lsource, float _f1, float _f2)
{ }
extern "C" void pfSpotLSourceDir(pfLightSource* _lsource, float _x, float _y, float _z)
{ }
extern "C" void pfSpotLightCone(pfLight* _light, float _f1, float _f2)
{ }
extern "C" void pfSpotLightDir(pfLight* _light, float _x, float _y, float _z)
{ }
extern "C" void pfStringBBox(pfString* _string, const pfBox* newbox)
{ }
extern "C" void pfStringGState(pfString* _string, pfGeoState *gs)
{ }
extern "C" void pfStringIsectMask(pfString* _string, uint _mask, int _setMode, int _bitOp)
{ }
extern "C" void pfStringSpacingScale(pfString* _string, float sx, float sy, float sz)
{ }
extern "C" int pfSwitchValFlux(pfSwitch* _switch, pfFlux *_valFlux)
{ return 0; }
extern "C" void pfTEnvComponent(pfTexEnv* _tenv, int _comp)
{ }
extern "C" void pfTGenMode(pfTexGen* _tgen, int _texCoord, int _mode)
{ }
extern "C" void pfTGenPlane(pfTexGen* _tgen, int _texCoord, float _x, float _y, float _z, float _d)
{ }
extern "C" void pfTLODBias(pfTexLOD* _tlod, float _biasS, float _biasT, float _biasR)
{ }
extern "C" void pfTLODRange(pfTexLOD* _tlod, float _min, float _max)
{ }
extern "C" void pfTexAnisotropy(pfTexture* _tex, const int _degree)
{ }
extern "C" void pfTexBorderColor(pfTexture* _tex, pfVec4 _clr)
{ }
extern "C" void pfTexBorderType(pfTexture* _tex, int _type)
{ }
extern "C" void pfTexDetail(pfTexture* _tex, int _l, pfTexture *_detail)
{ }
extern "C" void pfTexFrame(pfTexture* _tex, float _frame)
{ }
extern "C" void pfTexLevel(pfTexture* _tex, int _level, pfTexture* _ltex)
{ }
extern "C" void pfTexList(pfTexture* _tex, pfList *_list)
{ }
extern "C" void pfTexLoadImage(pfTexture* _tex, unsigned int* _image)
{ }
extern "C" void pfTexLoadMode(pfTexture* _tex, int _mode, int _val)
{ }
extern "C" void pfTexLoadOrigin(pfTexture* _tex, int _which, int _xo, int _yo)
{ }
extern "C" void pfTexLoadSize(pfTexture* _tex, int _xs, int _ys)
{ }
extern "C" void pfTexName(pfTexture* _tex, const char *_name)
{ }
extern "C" void pfTexSpline(pfTexture* _tex, int _type, pfVec2 *_pts, float _clamp)
{ }
extern "C" void pfUserDataSlot(pfObject* _obj, int _slot, void* data)
{ }
