#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfdoubletrans--pseudo-loader that translates a scene--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:33 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfdoubletrans

CXXFILES = \
        pfdoubletrans.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules
