#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfcsb						--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:33 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfcsb

C++FILES = \
        pfcsb.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules
