#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfsubstclip -- "substclip" pseudo-loader		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:35 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfsubstclip

CXXFILES = \
        pfsubstclip.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules
