#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfnff -- the NFF file loader			--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:34 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfnff

CFILES = \
        pfnff.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules
