#!/bin/sh
PFPATH=$PFROOT/perf/data:$PFROOT/perf/data/asddata:$PFROOT/usr/share/Performer/data/:$PFROOT/usr/share/Performer/data/asddata:$PFPATH
export PFPATH
./asdfly -m32 -f -l2 -L -N -p-9146.023438,-2363.947266,15380.807617 -e-69.739594,-4.535093,0.000000 $* simple.config
