#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfobj -- the Wavefront OBJ file loader		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:34 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfobj

CFILES = \
        pfobj.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules
