#-------------------------------------------------------------------------#
#-- Makefile for libpfdoublescale -- pseudo-loader that scales a scene	--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:33 $					--#
#-------------------------------------------------------------------------#

ifndef PFROOT
PFROOT = $(ROOT)
endif

include $(PFROOT)/usr/share/Performer/src/pfmakedefs.linux


#-- base name of library
LIBRARY	= libpfdoublescale

CXXFILES = \
        pfdoublescale.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules.linux
