#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfflt11 -- the FLIGHT v11 file loader		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:33 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfflt11

CFILES = \
	pfflt11_geom.c \
	pfflt11_hier.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules
