#-------------------------------------------------------------------------#
#-- Makefile for libpfarcinfo -- ARC/INFO ASCII Export Grid		--#
#--                              elevation data file loader		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:32 $					--#
#-------------------------------------------------------------------------#

ifndef PFROOT
PFROOT = $(ROOT)
endif

include $(PFROOT)/usr/share/Performer/src/pfmakedefs.linux


#-- base name of library
LIBRARY	= libpfarcinfo

CFILES = \
        pfarcinfo.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules.linux
