#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfsv -- the I3DM SV file loader			--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:35 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfsv

CFILES = \
        pfsv.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules
