#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfscale -- pseudo-loader that scales a scene	--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:35 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfscale

CXXFILES = \
        pfscale.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules
