#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfbpoly -- the Prisims ".bpoly" file loader		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:32 $					--#
#-------------------------------------------------------------------------#

ifndef PFROOT
PFROOT = $(ROOT)
endif

include $(PFROOT)/usr/share/Performer/src/pfmakedefs.linux


#-- base name of library
LIBRARY	= libpfbpoly

CFILES = \
        pfbpoly.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules.linux
