#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfbpoly -- the Prisims ".bpoly" file loader		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:32 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfbpoly

CFILES = \
        pfbpoly.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules
