#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfbin -- the BIN file loader			--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:32 $					--#
#-------------------------------------------------------------------------#

ifndef PFROOT
PFROOT = $(ROOT)
endif

include $(PFROOT)/usr/share/Performer/src/pfmakedefs.linux


#-- base name of library
LIBRARY	= libpfbin

CFILES = \
        pfbin.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules.linux
