#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfstar -- the Yale star-chart loader		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:35 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfstar

CFILES = \
        pfstar.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules
