#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfstlb -- the STL Binary file loader		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:35 $					--#
#-------------------------------------------------------------------------#

ifndef PFROOT
PFROOT = $(ROOT)
endif

include $(PFROOT)/usr/share/Performer/src/pfmakedefs.linux


#-- base name of library
LIBRARY	= libpfstlb

CFILES = \
        pfstlb.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules.linux
