#-------------------------------------------------------------------------#
#-- Makefile for libpfpfs -- "pfs" pseudo-loader		        --#
#-------------------------------------------------------------------------#

ifndef PFROOT
PFROOT = $(ROOT)
endif

include $(PFROOT)/usr/share/Performer/src/pfmakedefs.linux


#-- base name of library
LIBRARY	= libpfpfs

CXXFILES = \
        pfpfs.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules.linux
