#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfpfs -- "pfs" pseudo-loader		        --#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfpfs

CXXFILES = \
        pfpfs.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules
