#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpflodfix -- pseudo-loader that fixes pfLODs under SCSs -#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:33 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpflodfix

CXXFILES = \
        pflodfix.C


include $(PFROOT)/usr/share/Performer/src/pfmakerules
