#!smake
#-------------------------------------------------------------------------#
#-- Makefile for libpfevt -- File loader for EVT terrain data		--#
#-------------------------------------------------------------------------#
#-- RCS version information						--#
#--   $Revision: 1.1 $							--#
#--   $Date: 2000/11/21 21:39:33 $					--#
#-------------------------------------------------------------------------#

PFROOT ?= $(ROOT)
include $(PFROOT)/usr/share/Performer/src/pfmakedefs


#-- base name of library
LIBRARY	= libpfevt

CFILES = \
        pfevt.c


include $(PFROOT)/usr/share/Performer/src/pfmakerules
