/* pf_pfb_api.h - GENERATED by tools/harvest_pfb_api.py: the API
 * surface SGI's pfpfb.c needs beyond the base shim.  Tokens, typedefs
 * and declarations are extracted verbatim from the vendored SGI
 * headers.  Included from the shim's pf.h; do not hand-edit. */
#ifndef PFOSG_PF_PFB_API_H
#define PFOSG_PF_PFB_API_H

/* SGI's token defines expand to GL and IRIS-GL identifiers; pull in the
 * platform GL header and fill the EXT_texture-era gaps it no longer has */
#include <GL/gl.h>
#ifndef TX_SELECT
#define TX_SELECT 0x303
#endif
#ifndef GL_UNSIGNED_SHORT_5_5_5_1_EXT
#define GL_UNSIGNED_SHORT_5_5_5_1_EXT 0x8034
#endif
#ifndef GL_LUMINANCE8_ALPHA8_EXT
#define GL_LUMINANCE8_ALPHA8_EXT 0x8045
#endif
#ifndef GL_LUMINANCE12_ALPHA4_EXT
#define GL_LUMINANCE12_ALPHA4_EXT 0x8046
#endif
#ifndef GL_LUMINANCE12_ALPHA12_EXT
#define GL_LUMINANCE12_ALPHA12_EXT 0x8047
#endif
#ifndef GL_INTENSITY8_EXT
#define GL_INTENSITY8_EXT 0x804B
#endif
#ifndef GL_INTENSITY16_EXT
#define GL_INTENSITY16_EXT 0x804D
#endif
#ifndef GL_RGB4_EXT
#define GL_RGB4_EXT 0x804F
#endif
#ifndef GL_RGB5_EXT
#define GL_RGB5_EXT 0x8050
#endif
#ifndef GL_RGB12_EXT
#define GL_RGB12_EXT 0x8053
#endif
#ifndef GL_RGBA4_EXT
#define GL_RGBA4_EXT 0x8056
#endif
#ifndef GL_RGB5_A1_EXT
#define GL_RGB5_A1_EXT 0x8057
#endif
#ifndef GL_RGBA8_EXT
#define GL_RGBA8_EXT 0x8058
#endif
#ifndef GL_RGBA12_EXT
#define GL_RGBA12_EXT 0x805A
#endif
#ifndef GL_TEXTURE_WRAP_R_EXT
#define GL_TEXTURE_WRAP_R_EXT 0x8072
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* ---- opaque types ---- */
typedef struct islAppearance islAppearance;
typedef struct pfBillboard pfBillboard;
typedef struct pfCalligData pfCalligData;
typedef struct pfColortable pfColortable;
typedef struct pfCycleBuffer pfCycleBuffer;
typedef struct pfDirData pfDirData;
typedef struct pfDoubleDCS pfDoubleDCS;
typedef struct pfDoubleFCS pfDoubleFCS;
typedef struct pfDoubleSCS pfDoubleSCS;
typedef struct pfEngine pfEngine;
typedef struct pfFCS pfFCS;
typedef struct pfFlux pfFlux;
typedef struct pfIBRnode pfIBRnode;
typedef struct pfIBRtexture pfIBRtexture;
typedef struct pfLODState pfLODState;
typedef struct pfLayer pfLayer;
typedef struct pfMorph pfMorph;
typedef struct pfQueue pfQueue;
typedef struct pfRasterData pfRasterData;
typedef struct pfTexLOD pfTexLOD;

/* ---- real structs (verbatim from SGI headers) ---- */
typedef struct _pfASDFace
{
    int level;
    int tsid;
    int vert[3];
    int attr[3];
    int refvert[3];
    int sattr[3];
    int child[4];
    ushort gstateid;
    ushort mask;
} pfASDFace;

typedef struct _pfASDVert
{
    pfVec3 v0, vd;
    int neighborid[2];
    int vertid;
} pfASDVert;

typedef struct _pfASDLODRange
{
    float switchin;
    float morph;
} pfASDLODRange;

/* ---- callback types ---- */
typedef float (*pfASDEvalFuncType)(pfASD *_asd, pfVec3 _eyept, int _faceid, int _refvertid);
typedef void (*pfCalligFuncType)(pfCalligData *calligData);
typedef void (*pfEngineFuncType)(pfEngine *_engine);
typedef void (*pfImageCacheReadQueueFuncType)(pfImageTile *itile);
typedef void (*pfRasterFuncType)(pfRasterData *rasterData);
typedef void (*pfTileFileNameFuncType)(pfImageTile *tile);

/* ---- tokens (verbatim from SGI headers) ---- */
#define PFASD_CALLBACK		0x3
#define PFASD_COLORS		0x08
#define PFASD_COORDS		0x02
#define PFASD_DIST		0x1
#define PFASD_DIST_SQUARE	0x2
#define PFASD_FACES		0x20
#define PFASD_LODS		0x01
#define PFASD_NORMALS		0x04
#define PFASD_OVERALL_ATTR	0x40
#define PFASD_PER_VERTEX_ATTR	0x80
#define PFASD_TCOORDS		0x10
#define PFBB_AXIAL_ROT		PFSPRITE_AXIAL_ROT		
#define PFBB_POINT_ROT_EYE	PFSPRITE_POINT_ROT_EYE
#define PFBB_POINT_ROT_WORLD	PFSPRITE_POINT_ROT_WORLD		
#define PFBB_ROT		PFSPRITE_ROT
#define PFDCS_UNCONSTRAINED	0xffffffff
#define PFDD_MAX_RINGS 128   /* maximum number of rings of views */
#define PFDECAL_BASE	    		3
#define PFDECAL_BASE_DISPLACE		7
#define PFDECAL_BASE_FAST  		4
#define PFDECAL_BASE_HIGH_QUALITY   	5
#define PFDECAL_BASE_STENCIL		6
#define PFDECAL_LAYER	    		2
#define PFDECAL_LAYER_DISPLACE		11
#define PFDECAL_LAYER_DISPLACE_AWAY	12
#define PFDECAL_LAYER_FAST  		8
#define PFDECAL_LAYER_HIGH_QUALITY   	9
#define PFDECAL_LAYER_MASK		0xff00
#define PFDECAL_LAYER_OFFSET		0x10000
#define PFDECAL_LAYER_SHIFT		8
#define PFDECAL_LAYER_STENCIL		10
#define PFDECAL_MODE_MASK		0x000f
#define PFDECAL_OFF	    		0
#define PFENG_ALIGN		4
#define PFENG_ANIMATE		6
#define PFENG_BBOX		7
#define PFENG_MATRIX		5
#define PFENG_MATRIX_MODE	2
#define PFENG_MATRIX_POST_MULT	1
#define PFENG_MORPH		2
#define PFENG_RANGE_CHECK	1
#define PFENG_SUM		1
#define PFENG_TIME		9
#define PFENG_TIME_MODE		3
#define PFENG_TIME_SWING	1
#define PFENG_TRANSFORM		3
#define PFENG_USER_FUNCTION	8
#define PFFCS_UNCONSTRAINED	0xffffffff
#define PFFLUX_BUFFERS_SPECIFIED	1
#define PFFLUX_COPY_LAST_DATA	2
#define PFFLUX_ON_DEMAND	1
#define PFFLUX_PUSH		0
#define PFFOG_VTX_EXP	    	GL_EXP
#define PFFOG_VTX_EXP2	    	GL_EXP2
#define PFFONT_BBOX		1
#define	PFFONT_CHAR_SPACING	0
#define PFFONT_CHAR_SPACING_FIXED	0
#define PFFONT_CHAR_SPACING_VARIABLE	1
#define PFFONT_GSTATE		0
#define PFFONT_NAME		3
#define PFFONT_NUM_CHARS	1
#define PFFONT_RETURN_CHAR	2
#define PFFONT_SPACING		2
#define PFFONT_UNIT_SCALE	0
#define PFGS_COMPILE_GL     	4
#define PFGS_FLATSHADE	    	2
#define PFGS_WIREFRAME	    	3
#define PFHL_BGPAT    	    0x2
#define PFHL_FGPAT    	    0x1
#define PFHL_FILLPAT2	    (0x0040 | PFHL_FILLPAT) /* 2-pass patterning */
#define PFHL_FILL_R	    0x0100 /* reverse fg and bf colors for fill */
#define PFHL_LINESPAT2	    (0x008 | PFHL_LINESPAT) /* 2-pass patterning */
#define PFIBRN_TEXCOORDS_DEFINED   (1<<2) /* set automatically when setProxyTexCoords() is called */
#define PFIBRN_VARY_PROXY_GEOSETS  (1<<1) /* one group of geosets per view  */
#define PFIBR_NEAREST           (1<<3)
#define PFIBR_USE_PROXY         (1<<6)
#define PFIMAGECACHE_AUTOCENTER				0x1
#define PFIMAGECACHE_AUTOCREATE_STREAMSERVER_QUEUES 	0x2
#define PFIMAGECACHE_AUTOSET_TILE_FILENAME		0x3
#define PFIMAGECACHE_AUTOSET_TILE_READQUEUE		0x4
#define PFIMAGECACHE_R_DIMENSION			0x2
#define PFIMAGECACHE_S_DIMENSION			0x0
#define PFIMAGECACHE_TILE_FILENAMEARG_CACHENAME		10
#define PFIMAGECACHE_TILE_FILENAMEARG_FILENUM_R		13
#define PFIMAGECACHE_TILE_FILENAMEARG_FILENUM_S		11
#define PFIMAGECACHE_TILE_FILENAMEARG_FILENUM_T		12
#define PFIMAGECACHE_TILE_FILENAMEARG_STREAMSERVERNAME	9
#define PFIMAGECACHE_TILE_FILENAMEARG_TILENUM_R		5
#define PFIMAGECACHE_TILE_FILENAMEARG_TILENUM_S		3
#define PFIMAGECACHE_TILE_FILENAMEARG_TILENUM_T		4
#define PFIMAGECACHE_TILE_FILENAMEARG_TILEORG_R		8
#define PFIMAGECACHE_TILE_FILENAMEARG_TILEORG_S		6
#define PFIMAGECACHE_TILE_FILENAMEARG_TILEORG_T		7
#define PFIMAGECACHE_TILE_FILENAMEARG_VSIZE_R		2
#define PFIMAGECACHE_TILE_FILENAMEARG_VSIZE_S		0
#define PFIMAGECACHE_TILE_FILENAMEARG_VSIZE_T		1
#define PFIMAGECACHE_T_DIMENSION			0x1
#define PFLODSTATE_RANGE_RANGEOFFSET 		0
#define PFLODSTATE_RANGE_RANGESCALE		1
#define PFLODSTATE_RANGE_STRESSOFFSET		4
#define PFLODSTATE_RANGE_STRESSSCALE		5
#define PFLODSTATE_TRANSITION_RANGEOFFSET	2
#define PFLODSTATE_TRANSITION_RANGESCALE	3
#define PFLODSTATE_TRANSITION_STRESSOFFSET	6
#define PFLODSTATE_TRANSITION_STRESSSCALE	7
#define PFLPS_DIR_MODE          50
#define PFLPS_DIR_MODE_ALPHA    1
#define PFLPS_DIR_MODE_OFF      0
#define PFLPS_DIR_MODE_ON       1
#define PFLPS_DIR_MODE_TEX      2
#define PFLPS_DRAW_MODE		70
#define PFLPS_DRAW_MODE_CALLIGRAPHIC	1
#define PFLPS_DRAW_MODE_RASTER	0
#define PFLPS_FOG_MODE          30
#define PFLPS_FOG_MODE_ALPHA    1
#define PFLPS_FOG_MODE_OFF      0
#define PFLPS_FOG_MODE_ON       1
#define PFLPS_FOG_MODE_TEX      2
#define PFLPS_FOG_SCALE         300
#define PFLPS_INTENSITY         400
#define PFLPS_MAX_DEFOCUS	701
#define PFLPS_MIN_DEFOCUS	700
#define PFLPS_QUALITY_MODE	80
#define PFLPS_QUALITY_MODE_HIGH 0
#define PFLPS_QUALITY_MODE_LOW 2
#define PFLPS_QUALITY_MODE_MEDIUM 1
#define PFLPS_RANGE_MODE        40
#define PFLPS_RANGE_MODE_DEPTH  0
#define PFLPS_RANGE_MODE_TRUE   1
#define PFLPS_SHAPE_MODE        60
#define PFLPS_SHAPE_MODE_BI     1
#define PFLPS_SHAPE_MODE_BI_COLOR       2
#define PFLPS_SHAPE_MODE_UNI    0
#define PFLPS_SIGNIFICANCE	600
#define PFLPS_SIZE_ACTUAL       101
#define PFLPS_SIZE_DIFF_THRESH  500
#define PFLPS_SIZE_MAX_PIXEL    102
#define PFLPS_SIZE_MIN_PIXEL    100
#define PFLPS_SIZE_MODE         10
#define PFLPS_SIZE_MODE_OFF     0
#define PFLPS_SIZE_MODE_ON      1
#define PFLPS_TRANSP_CLAMP      203
#define PFLPS_TRANSP_EXPONENT   201
#define PFLPS_TRANSP_MODE       20
#define PFLPS_TRANSP_MODE_ALPHA 1
#define PFLPS_TRANSP_MODE_OFF   0
#define PFLPS_TRANSP_MODE_ON    1
#define PFLPS_TRANSP_MODE_TEX   2       
#define PFLPS_TRANSP_PIXEL_SIZE 200     
#define PFLPS_TRANSP_SCALE      202
#define	PFLS_FOG_ENABLE			2
#define	PFLS_FREEZE_SHADOWS		3
#define PFLS_INTENSITY			13
#define PFLS_PROJTEX_ENABLE		0
#define PFLS_PROJ_FOG			22
#define PFLS_PROJ_FRUST			23
#define PFLS_PROJ_TEX			21
#define PFLS_SHADOW_DISPLACE_OFFSET	11
#define PFLS_SHADOW_DISPLACE_SCALE	10	
#define	PFLS_SHADOW_ENABLE		1
#define PFLS_SHADOW_SIZE		12	
#define PFLS_SHADOW_TEX			20
#define PFMTL_CMODE_AMBIENT	GL_AMBIENT
#define PFMTL_CMODE_COLOR	0	/* NA in OpenGL */
#define PFMTL_CMODE_DIFFUSE	GL_DIFFUSE
#define PFMTL_CMODE_EMISSION	GL_EMISSION
#define PFMTL_CMODE_SPECULAR	GL_SPECULAR
#define PFNFY_INTERNAL_DEBUG	7
#define PFSEQ_CYCLE	0
#define PFSEQ_PAUSE	2
#define PFSEQ_RESUME	3
#define PFSEQ_START	1
#define PFSEQ_STOP	0
#define PFSEQ_SWING	1
#define PFSPRITE_AXIAL_ROT		0
#define PFSPRITE_POINT_ROT_EYE		1
#define PFSPRITE_POINT_ROT_WORLD	2
#define PFSPRITE_ROT			0
#define PFSTATE_COLORTABLE    	             0x800 
#define PFSTATE_DECAL	    	             0x4000
#define PFSTATE_ENCOLORTABLE   	             0x400
#define PFSTATE_ENTEXLOD	             0x10000000
#define PFSTATE_TEXLOD		             0x20000000
#define PFSTR_CHAR		1
#define PFSTR_CHAR_SIZE		30
#define PFSTR_INT		4
#define PFSTR_SHORT		2
#define PFSWITCH_OFF		-2
#define PFSWITCH_ON		-1
#define PFTEX_ADD			0x00000200
#define PFTEX_ALPHA			0x00000008
#define PFTEX_BASE_APPLY		0
#define PFTEX_BASE_AUTO_SUBLOAD		1
#define PFTEX_BICUBIC			0x00000080
#define PFTEX_BORDER_COLOR		1
#define PFTEX_BORDER_NONE		0
#define PFTEX_BORDER_TEXELS		2
#define PFTEX_BYTE		GL_BYTE
#define PFTEX_CLAMP		GL_CLAMP
#define PFTEX_COLOR			0x00000004
#define PFTEX_DETAIL			0x00000040
#define PFTEX_DETAIL_SPLINE		3
#define PFTEX_DETAIL_TEXTURE		3
#define PFTEX_EXTERNAL_FORMAT		2
#define PFTEX_FAST_DEFINE		PFTEX_SUBLOAD_FORMAT
#define PFTEX_FLOAT		GL_FLOAT
#define PFTEX_GEN_MIPMAP_FORMAT		4
#define PFTEX_GEQUAL			0x00000800
#define PFTEX_IA_12 		GL_LUMINANCE12_ALPHA12_EXT
#define PFTEX_IA_8		GL_LUMINANCE8_ALPHA8_EXT
#define PFTEX_INT		GL_INT
#define PFTEX_INTERNAL_FORMAT		1
#define PFTEX_I_12A_4		GL_LUMINANCE12_ALPHA4_EXT
#define PFTEX_I_16		GL_INTENSITY16_EXT
#define PFTEX_LEQUAL			0x00000400
#define PFTEX_LINEAR			0x00002000
#define PFTEX_LIST_APPLY		0
#define PFTEX_LIST_AUTO_IDLE		1
#define PFTEX_LIST_AUTO_SUBLOAD		2
#define PFTEX_LOAD_BASE			2
#define PFTEX_LOAD_LIST			1
#define PFTEX_LOAD_SOURCE		3
#define PFTEX_LUMINANCE		GL_LUMINANCE
#define PFTEX_LUMINANCE_ALPHA	GL_LUMINANCE_ALPHA
#define PFTEX_MAGFILTER_ALPHA		(PFTEX_MAGFILTER | PFTEX_ALPHA)
#define PFTEX_MAGFILTER_COLOR		(PFTEX_MAGFILTER | PFTEX_COLOR)
#define PFTEX_MODULATE			0x00000100
#define PFTEX_ORIGIN_DEST		1
#define PFTEX_ORIGIN_SOURCE		0
#define PFTEX_PACK_16		GL_UNSIGNED_SHORT
#define PFTEX_PACK_8		GL_UNSIGNED_BYTE
#define PFTEX_QUADLINEAR		0x00010000
#define PFTEX_REPEAT		GL_REPEAT
#define PFTEX_RGB		GL_RGB
#define PFTEX_RGB5_A1		GL_RGB5_A1_EXT
#define PFTEX_RGBA		GL_RGBA
#define PFTEX_RGBA_12 		GL_RGBA12_EXT
#define PFTEX_RGBA_4		GL_RGBA4_EXT
#define PFTEX_RGBA_8		GL_RGBA8_EXT
#define PFTEX_RGB_12		GL_RGB12_EXT
#define PFTEX_RGB_4		GL_RGB4_EXT
#define PFTEX_RGB_5		GL_RGB5_EXT
#define PFTEX_SELECT		TX_SELECT
#define PFTEX_SHARPEN			0x00000020
#define PFTEX_SHARPEN_SPLINE		2
#define PFTEX_SHORT		GL_SHORT
#define PFTEX_SOURCE_FRAMEBUFFER	1
#define PFTEX_SOURCE_IMAGE		0
#define PFTEX_SOURCE_VIDEO		2
#define PFTEX_SUBLOAD_FORMAT		6
#define PFTEX_UNSIGNED_BYTE	GL_UNSIGNED_BYTE
#define PFTEX_UNSIGNED_INT	GL_UNSIGNED_INT
#define PFTEX_UNSIGNED_SHORT	GL_UNSIGNED_SHORT
#define PFTEX_UNSIGNED_SHORT_5_5_5_1	GL_UNSIGNED_SHORT_5_5_5_1_EXT
#define PFTEX_WRAP		TX_WRAP
#define PFTEX_WRAP_R		GL_TEXTURE_WRAP_R_EXT
#define PFTEX_WRAP_S		GL_TEXTURE_WRAP_S
#define PFTEX_WRAP_T		GL_TEXTURE_WRAP_T
#define PFTE_COMP_IA_GETS_BA	TV_IA_GETS_BA
#define PFTE_COMP_IA_GETS_RG	TV_IA_GETS_RG
#define PFTE_COMP_I_GETS_A	GL_PIXEL_MAP_I_TO_A
#define PFTE_COMP_I_GETS_B	GL_PIXEL_MAP_I_TO_B
#define PFTE_COMP_I_GETS_G	GL_PIXEL_MAP_I_TO_G
#define PFTE_COMP_I_GETS_I	GL_PIXEL_MAP_I_TO_I
#define PFTE_COMP_I_GETS_R	GL_PIXEL_MAP_I_TO_R
#define PFTE_COMP_OFF		0
#define PFTG_EYE_LINEAR			GL_EYE_LINEAR
#define PFTG_EYE_LINEAR_IDENT		0x23ff
#define PFTG_OBJECT_LINEAR		GL_OBJECT_LINEAR
#define PFTG_OFF			0
#define PFTG_SPHERE_MAP			GL_SPHERE_MAP
#define PFTLOAD_DEST_TEXTURE		0
#define PFTR_MS_ALPHA_MASK	6
#define PF_MAX_LIGHTS 8 /* XXX need to query opengl for max lights */
#define PF_Q		3
#define PF_S		0
#define PF_T		1
#ifndef PFHL_FILLPAT
#define PFHL_FILLPAT	    (0x0020 | PFHL_FILL)
#endif
#ifndef PFHL_LINESPAT
#define PFHL_LINESPAT	    (0x004 | PFHL_LINES)
#endif
#ifndef PFTEX_MAGFILTER
#define PFTEX_MAGFILTER			0x00000001
#endif
#ifndef TV_IA_GETS_BA
#define TV_IA_GETS_BA           0x360
#endif
#ifndef TV_IA_GETS_RG
#define TV_IA_GETS_RG           0x350
#endif
#ifndef TX_SELECT
#define TX_SELECT		0x303
#endif
#ifndef TX_WRAP
#define TX_WRAP			0x300
#endif
#ifndef PFHL_FILL
#define PFHL_FILL	    0x0010
#endif
#ifndef PFHL_LINES
#define PFHL_LINES	    0x001
#endif

/* ---- declarations (verbatim from SGI headers) ---- */
extern DLLEXPORT void pfASDAttr(pfASD* _asd, int _which, int _type, int _size, void *_attr);
extern DLLEXPORT void pfASDConfig(pfASD* _asd);
extern DLLEXPORT void pfASDEvalFunc(pfASD* _asd, pfASDEvalFuncType _eval);
extern DLLEXPORT void pfASDEvalMethod(pfASD* _asd, int method);
extern DLLEXPORT void pfASDGStates(pfASD* _asd, pfGeoState **gs, int num);
extern DLLEXPORT void pfASDMaxMorphDepth(pfASD* _asd, int _m, float __morphweightconstraint);
extern DLLEXPORT void pfASDMorphAttrs(pfASD* _asd, int _mc);
extern DLLEXPORT void pfASDNumBaseFaces(pfASD* _asd, int num);
extern DLLEXPORT void pfBboardAxis(pfBillboard* _bboard, const PFVEC3 axis);
extern DLLEXPORT void pfBboardMode(pfBillboard* _bboard, int _mode, int _val);
extern DLLEXPORT void pfBboardPos(pfBillboard* _bboard, int i, const PFVEC3 pos);
extern DLLEXPORT void pfBboardPosFlux(pfBillboard* _bboard, pfFlux *_flux);
extern DLLEXPORT void pfCBufferChanged(pfCycleBuffer* cBuf);
extern DLLEXPORT void pfCalligFunc(pfLPointState* _lpstate, pfCalligFuncType _calligraphicCallback, void *_data);
extern DLLEXPORT void pfClipTextureCenter(pfClipTexture* _cliptexture, int _s, int _t, int _r);
extern DLLEXPORT void pfClipTextureClipSize(pfClipTexture* _cliptexture, int _clipSize);
extern DLLEXPORT void pfClipTextureInvalidBorder(pfClipTexture* _cliptexture, int _nTexels);
extern DLLEXPORT void pfClipTextureLODRange(pfClipTexture* _cliptexture, float _min, float _max);
extern DLLEXPORT void pfClipTextureLevel(pfClipTexture* _cliptexture, int _level, pfObject* _levelObj);
extern DLLEXPORT void pfClipTextureLevelPhaseMargin(pfClipTexture* _cliptexture, int level, int size);
extern DLLEXPORT void pfClipTextureLevelPhaseShift(pfClipTexture* _cliptexture, int level, int phaseShiftS, int phaseShiftT, int phaseShiftR);
extern DLLEXPORT void pfClipTextureNumEffectiveLevels(pfClipTexture* _cliptexture, int _levels);
extern DLLEXPORT void pfClipTextureVirtualLODOffset(pfClipTexture* _cliptexture, int _offset);
extern DLLEXPORT void pfClipTextureVirtualSize(pfClipTexture* _cliptexture, int _width, int _height, int _depth);
extern DLLEXPORT int pfCtabColor(pfColortable* _ctab, int _index, PFVEC4 _acolor);
extern DLLEXPORT void pfDCSMatType(pfDCS* _dcs, uint val);
extern DLLEXPORT void pfDoubleDCSMat(pfDoubleDCS* _doubledcs, PFMATRIX4D m);
extern DLLEXPORT void pfDoubleDCSMatType(pfDoubleDCS* _doubledcs, uint val);
extern DLLEXPORT void pfDoubleFCSMatType(pfDoubleFCS* _doublefcs, uint val);
extern DLLEXPORT void pfEngineDst(pfEngine* _engine, void *_data, ushort *_ilist, int _offset, int _stride);
extern DLLEXPORT void pfEngineEvaluationRange(pfEngine* _engine, PFVEC3 _center, float _min, float _max);
extern DLLEXPORT void pfEngineIterations(pfEngine* _engine, int _iterations, int _itemsPer);
extern DLLEXPORT void pfEngineMask(pfEngine* _engine, uint _mask);
extern DLLEXPORT void pfEngineMode(pfEngine* _engine, int _mode, int _val);
extern DLLEXPORT void pfEngineSrc(pfEngine* _engine, int _index, void *_data, ushort *_ilist, int _icount, int _offset, int _stride);
extern DLLEXPORT void pfEngineUserFunction(pfEngine* _engine, pfEngineFuncType _func);
extern DLLEXPORT void pfFCSMatType(pfFCS* _fcs, uint val);
extern DLLEXPORT void pfFluxInitData(pfFlux* _flux, void *_data);
extern DLLEXPORT void pfFluxMask(pfFlux* _flux, uint _mask);
extern DLLEXPORT void pfFluxMode(pfFlux* _flux, int _mode, int _val);
extern DLLEXPORT void pfFluxSyncGroup(pfFlux* _flux, uint _syncGroup);
extern DLLEXPORT void pfFogOffsets(pfFog* _fog, float _onset, float _opaque);
extern DLLEXPORT void pfFogRamp(pfFog* _fog, int _points, float* _range, float* _density, float _bias);
extern DLLEXPORT void pfFontAttr(pfFont* _font, int _which, void *attr);
extern DLLEXPORT void pfFontCharGSet(pfFont* _font, int _ascii, pfGeoSet *_gset);
extern DLLEXPORT void pfFontCharSpacing(pfFont* _font, int _ascii, PFVEC3 _spacing);
extern DLLEXPORT void pfFontMode(pfFont* _font, int mode, int val);
extern DLLEXPORT void pfFontVal(pfFont* _font, int _which, float _val);
extern DLLEXPORT void pfGSetAppearance(pfGeoSet* _gset, islAppearance *appearance_);
extern DLLEXPORT void pfGSetBBox(pfGeoSet* _gset, pfBox* _box, int _mode);
extern DLLEXPORT void pfGSetBBoxFlux(pfGeoSet* _gset, pfFlux* _flux);
extern DLLEXPORT void pfGSetDecalPlane(pfGeoSet* _gset, pfPlane *_plane);
extern DLLEXPORT void pfGSetDrawBin(pfGeoSet* _gset, short bin);
extern DLLEXPORT void pfGSetDrawMode(pfGeoSet* _gset, int _mode, int _val);
extern DLLEXPORT void pfGSetDrawOrder(pfGeoSet* _gset, unsigned int order);
extern DLLEXPORT void pfGSetGStateIndex(pfGeoSet* _gset, int _id);
extern DLLEXPORT void pfGSetHlight(pfGeoSet* _gset, pfHighlight *_hlight);
extern DLLEXPORT void pfGSetIsectMask(pfGeoSet* _gset, unsigned int _mask, int _setMode, int _bitOp);
extern DLLEXPORT void pfGSetLineWidth(pfGeoSet* _gset, float _width);
extern DLLEXPORT void pfGSetMultiAttr(pfGeoSet* _gset, int _attr, int _index, int _bind, void* _alist, unsigned short* _ilist);
extern DLLEXPORT void pfGSetPntSize(pfGeoSet* _gset, float _s);
extern DLLEXPORT void pfGStateInherit(pfGeoState* _gstate, uint64_t _mask);
extern DLLEXPORT void pfGStateMultiAttr(pfGeoState* _gstate, uint64_t _attr, int _index, void* _a);
extern DLLEXPORT void pfGStateMultiMode(pfGeoState* _gstate, uint64_t _attr, int _index, int _a);
extern DLLEXPORT void pfGetASDAttr(pfASD* _asd, int _which, int *_type, int *_size, void **_attr);
extern DLLEXPORT pfType* pfGetASDClassType(void);
extern DLLEXPORT pfASDEvalFuncType pfGetASDEvalFunc(pfASD* _asd);
extern DLLEXPORT int pfGetASDEvalMethod(pfASD* _asd);
extern DLLEXPORT pfGeoState* pfGetASDGState(pfASD* _asd, int num);
extern DLLEXPORT void pfGetASDMaxMorphDepth(pfASD* _asd, int *_m, float *__morphweightconstraint);
extern DLLEXPORT int pfGetASDMorphAttrs(pfASD* _asd);
extern DLLEXPORT int pfGetASDNumBaseFaces(pfASD* _asd);
extern DLLEXPORT int pfGetASDNumGStates(pfASD* _asd);
extern DLLEXPORT void* pfGetArena(void *data);
extern DLLEXPORT void pfGetBboardAxis(pfBillboard* _bboard, PFVEC3 axis);
extern DLLEXPORT pfType* pfGetBboardClassType(void);
extern DLLEXPORT int pfGetBboardMode(pfBillboard* _bboard, int _mode);
extern DLLEXPORT void pfGetBboardPos(pfBillboard* _bboard, int i, PFVEC3 pos);
extern DLLEXPORT pfFlux* pfGetBboardPosFlux(pfBillboard* _bboard);
extern DLLEXPORT pfCycleBuffer* pfGetCBuffer(void *data);
extern DLLEXPORT pfType* pfGetCBufferClassType(void);
extern DLLEXPORT void pfGetCalligFunc(pfLPointState* _lpstate, pfCalligFuncType *_calligraphicCallback, void **_data);
extern DLLEXPORT void pfGetClipTextureCenter(pfClipTexture* _cliptexture, int *_s, int *_t, int *_r);
extern DLLEXPORT pfType* pfGetClipTextureClassType(void);
extern DLLEXPORT int pfGetClipTextureClipSize(pfClipTexture* _cliptexture);
extern DLLEXPORT uint pfGetClipTextureDTRMode(pfClipTexture* _cliptexture);
extern DLLEXPORT int pfGetClipTextureInvalidBorder(pfClipTexture* _cliptexture);
extern DLLEXPORT void pfGetClipTextureLODRange(pfClipTexture* _cliptexture, float *_min, float *_max);
extern DLLEXPORT pfObject* pfGetClipTextureLevel(pfClipTexture* _cliptexture, int _level);
extern DLLEXPORT int pfGetClipTextureLevelPhaseMargin(pfClipTexture* _cliptexture, int level);
extern DLLEXPORT void pfGetClipTextureLevelPhaseShift(pfClipTexture* _cliptexture, int level, int *phaseShiftS, int *phaseShiftT, int *phaseShiftR);
extern DLLEXPORT pfClipTexture* pfGetClipTextureMaster(const pfClipTexture* _cliptexture);
extern DLLEXPORT int pfGetClipTextureNumEffectiveLevels(pfClipTexture* _cliptexture);
extern DLLEXPORT int pfGetClipTextureVirtualLODOffset(pfClipTexture* _cliptexture);
extern DLLEXPORT void pfGetClipTextureVirtualSize(pfClipTexture* _cliptexture, int *_width, int *_height, int *_depth);
extern DLLEXPORT pfType* pfGetCtabClassType(void);
extern DLLEXPORT pfVec4* pfGetCtabColors(const pfColortable* _ctab);
extern DLLEXPORT int pfGetCtabSize(const pfColortable* _ctab);
extern DLLEXPORT void* pfGetCurCBufferData(const pfCycleBuffer* cBuf);
extern DLLEXPORT pfType* pfGetDCSClassType(void);
extern DLLEXPORT uint pfGetDCSMatType(const pfDCS* _dcs);
extern DLLEXPORT void pfGetDirDataDirections(pfDirData* _dirdata, int *num, pfVec3 **directions);
extern DLLEXPORT int pfGetDirDataNumGroups(pfDirData* _dirdata, int *viewsPerGroup);
extern DLLEXPORT pfType* pfGetDoubleDCSClassType(void);
extern DLLEXPORT void pfGetDoubleDCSMat(pfDoubleDCS* _doubledcs, PFMATRIX4D m);
extern DLLEXPORT uint pfGetDoubleDCSMatType(const pfDoubleDCS* _doubledcs);
extern DLLEXPORT pfType* pfGetDoubleFCSClassType(void);
extern DLLEXPORT pfFlux* pfGetDoubleFCSFlux(pfDoubleFCS* _doublefcs);
extern DLLEXPORT uint pfGetDoubleFCSMatType(const pfDoubleFCS* _doublefcs);
extern DLLEXPORT pfType* pfGetDoubleSCSClassType(void);
extern DLLEXPORT void pfGetDoubleSCSMat(pfDoubleSCS* _doublescs, PFMATRIX4D m);
extern DLLEXPORT void pfGetEngineDst(const pfEngine* _engine, void **_data, ushort **_ilist, int *_offset, int *_stride);
extern DLLEXPORT void pfGetEngineEvaluationRange(const pfEngine* _engine, PFVEC3 _center, float *_min, float *_max);
extern DLLEXPORT int pfGetEngineFunction(const pfEngine* _engine);
extern DLLEXPORT void pfGetEngineIterations(const pfEngine* _engine, int *_iterations, int *_itemsPer);
extern DLLEXPORT uint pfGetEngineMask(const pfEngine* _engine);
extern DLLEXPORT int pfGetEngineMode(const pfEngine* _engine, int _mode);
extern DLLEXPORT int pfGetEngineNumSrcs(const pfEngine* _engine);
extern DLLEXPORT void pfGetEngineSrc(const pfEngine* _engine, int _index, void **_data, ushort **_ilist, int *_icount, int *_offset, int *_stride);
extern DLLEXPORT pfEngineFuncType pfGetEngineUserFunction(const pfEngine* _engine);
extern DLLEXPORT pfType* pfGetFCSClassType(void);
extern DLLEXPORT pfFlux* pfGetFCSFlux(pfFCS* _fcs);
extern DLLEXPORT uint pfGetFCSMatType(const pfFCS* _fcs);
extern DLLEXPORT pfFlux* pfGetFlux(void *_data);
extern DLLEXPORT pfType* pfGetFluxClassType(void);
extern DLLEXPORT pfEngine* pfGetFluxClientEngine(const pfFlux* _flux, int _index);
extern DLLEXPORT void* pfGetFluxCurData(pfFlux* _flux);
extern DLLEXPORT size_t pfGetFluxDataSize(const pfFlux* _flux);
extern DLLEXPORT uint pfGetFluxMask(const pfFlux* _flux);
extern DLLEXPORT int pfGetFluxMode(const pfFlux* _flux, int _mode);
extern DLLEXPORT int pfGetFluxNamedSyncGroup(const char *_name);
extern DLLEXPORT int pfGetFluxNumBuffers(const pfFlux* _flux, int _type);
extern DLLEXPORT int pfGetFluxNumClientEngines(const pfFlux* _flux);
extern DLLEXPORT int pfGetFluxNumSrcEngines(const pfFlux* _flux);
extern DLLEXPORT pfEngine* pfGetFluxSrcEngine(const pfFlux* _flux, int _index);
extern DLLEXPORT uint pfGetFluxSyncGroup(const pfFlux* _flux);
extern DLLEXPORT const char* pfGetFluxSyncGroupName(uint _syncGroup);
extern DLLEXPORT pfType* pfGetFogClassType(void);
extern DLLEXPORT void pfGetFogColor(const pfFog* _fog, float* _r, float* _g, float* _b);
extern DLLEXPORT void pfGetFogOffsets(const pfFog* _fog, float *_onset, float *_opaque);
extern DLLEXPORT void pfGetFogRamp(const pfFog* _fog, int* _points, float* _range, float* _density, float* _bias);
extern DLLEXPORT void pfGetFogRange(const pfFog* _fog, float* _onset, float* _opaque);
extern DLLEXPORT int pfGetFogType(const pfFog* _fog);
extern DLLEXPORT void* pfGetFontAttr(pfFont* _font, int _which);
extern DLLEXPORT pfGeoSet* pfGetFontCharGSet(pfFont* _font, int _ascii);
extern DLLEXPORT const pfVec3* pfGetFontCharSpacing(pfFont* _font, int _ascii);
extern DLLEXPORT pfType* pfGetFontClassType(void);
extern DLLEXPORT int pfGetFontMode(pfFont* _font, int mode);
extern DLLEXPORT float pfGetFontVal(pfFont* _font, int _which);
extern DLLEXPORT pfFlux* pfGetFrameTimeFlux(void);
extern DLLEXPORT islAppearance* pfGetGSetAppearance(const pfGeoSet* _gset);
extern DLLEXPORT int pfGetGSetAttrBind(const pfGeoSet* _gset, int _attr);
extern DLLEXPORT int pfGetGSetAttrRange(const pfGeoSet* _gset, int _attr, int *_min, int *_max);
extern DLLEXPORT int pfGetGSetBBox(pfGeoSet* _gset, pfBox* _box);
extern DLLEXPORT pfFlux* pfGetGSetBBoxFlux(pfGeoSet* _gset);
extern DLLEXPORT pfType* pfGetGSetClassType(void);
extern DLLEXPORT pfPlane* pfGetGSetDecalPlane(const pfGeoSet* _gset);
extern DLLEXPORT int pfGetGSetDrawBin(const pfGeoSet* _gset);
extern DLLEXPORT int pfGetGSetDrawMode(const pfGeoSet* _gset, int _mode);
extern DLLEXPORT unsigned int pfGetGSetDrawOrder(const pfGeoSet* _gset);
extern DLLEXPORT int pfGetGSetGStateIndex(const pfGeoSet* _gset);
extern DLLEXPORT pfHighlight* pfGetGSetHlight(const pfGeoSet* _gset);
extern DLLEXPORT unsigned int pfGetGSetIsectMask(const pfGeoSet* _gset);
extern DLLEXPORT float pfGetGSetLineWidth(const pfGeoSet* _gset);
extern DLLEXPORT int pfGetGSetMultiAttrBind(const pfGeoSet* _gset, int _attr, int _index);
extern DLLEXPORT void pfGetGSetMultiAttrLists(const pfGeoSet* _gset, int _attr, int _index, void** _alist, unsigned short** _ilist);
extern DLLEXPORT int pfGetGSetMultiAttrRange(const pfGeoSet* _gset, int _attr, int _index, int *_min, int *_max);
extern DLLEXPORT float pfGetGSetPntSize(const pfGeoSet* _gset);
extern DLLEXPORT int* pfGetGSetPrimLengths(const pfGeoSet* _gset);
extern DLLEXPORT void* pfGetGStateAttr(const pfGeoState* _gstate, uint64_t _attr);
extern DLLEXPORT pfType* pfGetGStateClassType(void);
extern DLLEXPORT uint64_t pfGetGStateInherit(const pfGeoState* _gstate);
extern DLLEXPORT int pfGetGStateMode(const pfGeoState* _gstate, uint64_t _attr);
extern DLLEXPORT void* pfGetGStateMultiAttr(const pfGeoState* _gstate, uint64_t _attr, int _index);
extern DLLEXPORT int pfGetGStateMultiMode(const pfGeoState* _gstate, uint64_t _attr, int _index);
extern DLLEXPORT float pfGetGStateVal(const pfGeoState* _gstate, uint64_t _attr);
extern DLLEXPORT pfQueue* pfGetGlobalReadQueue(void);
extern DLLEXPORT float pfGetHlightAlpha(const pfHighlight* _hlight);
extern DLLEXPORT pfType* pfGetHlightClassType(void);
extern DLLEXPORT void pfGetHlightColor(const pfHighlight* _hlight, unsigned int _which, float *_r, float *_g, float *_b);
extern DLLEXPORT void pfGetHlightFillPat(const pfHighlight* _hlight, int _which, unsigned int *_pat);
extern DLLEXPORT pfGeoState* pfGetHlightGState(const pfHighlight* _hlight);
extern DLLEXPORT int pfGetHlightGStateIndex(const pfHighlight* _hlight);
extern DLLEXPORT unsigned short pfGetHlightLinePat(const pfHighlight* _hlight, int _which);
extern DLLEXPORT float pfGetHlightLineWidth(const pfHighlight* _hlight);
extern DLLEXPORT unsigned int pfGetHlightMode(const pfHighlight* _hlight);
extern DLLEXPORT void pfGetHlightNormalLength(const pfHighlight* _hlight, float *_len, float *_bboxScale);
extern DLLEXPORT float pfGetHlightPntSize(const pfHighlight* _hlight);
extern DLLEXPORT pfTexEnv* pfGetHlightTEnv(const pfHighlight* _hlight);
extern DLLEXPORT pfTexGen* pfGetHlightTGen(const pfHighlight* _hlight);
extern DLLEXPORT pfTexture* pfGetHlightTex(const pfHighlight* _hlight);
extern DLLEXPORT void pfGetIBRnodeAngles(pfIBRnode* _ibrnode, int i, float *horAngle, float *verAngle);
extern DLLEXPORT pfType* pfGetIBRnodeClassType(void);
extern DLLEXPORT int pfGetIBRnodeFlags(const pfIBRnode* _ibrnode, int which);
extern DLLEXPORT pfIBRtexture* pfGetIBRnodeIBRtexture(pfIBRnode* _ibrnode);
extern DLLEXPORT int pfGetIBRnodeNumAngles(pfIBRnode* _ibrnode);
extern DLLEXPORT pfVec2*** pfGetIBRnodeProxyTexCoords(pfIBRnode* _ibrnode);
extern DLLEXPORT pfDirData* pfGetIBRtextureDirData(pfIBRtexture* _ibrtexture);
extern DLLEXPORT float pfGetIBRtextureDirection(const pfIBRtexture* _ibrtexture);
extern DLLEXPORT int pfGetIBRtextureFlags(const pfIBRtexture* _ibrtexture, int which);
extern DLLEXPORT void pfGetIBRtextureIBRTextures(pfIBRtexture* _ibrtexture, pfTexture ***textures, int *numTex);
extern DLLEXPORT void pfGetIBRtextureIBRdirections(pfIBRtexture* _ibrtexture, pfVec3 **directions, int *numDirs);
extern DLLEXPORT pfType* pfGetImageCacheClassType(void);
extern DLLEXPORT const char* pfGetImageCacheFileStreamServer(pfImageCache* _imagecache, int _dim, int _which);
extern DLLEXPORT void pfGetImageCacheImageSize(pfImageCache* _imagecache, int *_sizeS, int *_sizeT, int *_sizeR);
extern DLLEXPORT pfImageCache* pfGetImageCacheMaster(const pfImageCache* _imagecache);
extern DLLEXPORT void pfGetImageCacheMemRegionOrg(pfImageCache* _imagecache, int *_orgTileS, int *_orgTileT, int *_orgTileR);
extern DLLEXPORT void pfGetImageCacheMemRegionSize(pfImageCache* _imagecache, int *_sizeS, int *_sizeT, int *_sizeR);
extern DLLEXPORT int pfGetImageCacheMode(pfImageCache* _imagecache, int _mode);
extern DLLEXPORT const char* pfGetImageCacheName(pfImageCache* _imagecache);
extern DLLEXPORT int pfGetImageCacheNumStreamServers(const pfImageCache* _imagecache, int _dim);
extern DLLEXPORT pfImageTile* pfGetImageCacheProtoTile(pfImageCache* _imagecache);
extern DLLEXPORT pfImageCacheReadQueueFuncType pfGetImageCacheReadQueueFunc(pfImageCache* _imagecache);
extern DLLEXPORT pfQueue* pfGetImageCacheStreamServerQueue(pfImageCache* _imagecache, int _dim, int _which);
extern DLLEXPORT void pfGetImageCacheTex(pfImageCache* _imagecache, void **_dst, int *_lvl, int *_type);
extern DLLEXPORT void pfGetImageCacheTexRegionOrg(pfImageCache* _imagecache, int *_originS, int *_originT, int *_originR);
extern DLLEXPORT void pfGetImageCacheTexRegionSize(pfImageCache* _imagecache, int *_sizeS, int *_sizeT, int *_sizeR);
extern DLLEXPORT void pfGetImageCacheTexSize(pfImageCache* _imagecache, int *_s, int *_t, int *_r);
extern DLLEXPORT void pfGetImageCacheTileFileNameFormat(pfImageCache* _imagecache, const char **_fmtString, int *_nArgs, const int **_argList);
extern DLLEXPORT pfTileFileNameFuncType pfGetImageCacheTileFileNameFunc(pfImageCache* _imagecache);
extern DLLEXPORT pfImageTile* pfGetImageTileDefaultTile(pfImageTile* _imagetile);
extern DLLEXPORT int pfGetImageTileDefaultTileMode(pfImageTile* _imagetile);
extern DLLEXPORT int pfGetImageTileFileImageFormat(pfImageTile* _imagetile);
extern DLLEXPORT int pfGetImageTileFileImageType(pfImageTile* _imagetile);
extern DLLEXPORT const char* pfGetImageTileFileName(pfImageTile* _imagetile);
extern DLLEXPORT void pfGetImageTileFileTile(pfImageTile* _imagetile, int *_tileS, int *_tileT, int *_tileR);
extern DLLEXPORT int pfGetImageTileHeaderOffset(pfImageTile* _imagetile);
extern DLLEXPORT int pfGetImageTileMemImageFormat(pfImageTile* _imagetile);
extern DLLEXPORT int pfGetImageTileMemImageType(pfImageTile* _imagetile);
extern DLLEXPORT void pfGetImageTileMemInfo(pfImageTile* _imagetile, int *_psize, int *_lock);
extern DLLEXPORT const char* pfGetImageTileName(pfImageTile* _imagetile);
extern DLLEXPORT void pfGetImageTileNumFileTiles(pfImageTile* _imagetile, int *_nTilesS, int *_nTilesT, int *_nTilesR);
extern DLLEXPORT void pfGetImageTileOrigin(pfImageTile* _imagetile, int *_s, int *_t, int *_r);
extern DLLEXPORT int pfGetImageTilePriority(pfImageTile* _imagetile);
extern DLLEXPORT pfReadImageTileFuncType pfGetImageTileReadFunc(pfImageTile* _imagetile);
extern DLLEXPORT pfQueue* pfGetImageTileReadQueue(pfImageTile* _imagetile);
extern DLLEXPORT void pfGetImageTileSize(pfImageTile* _imagetile, int *_w, int *_h,int *_d);
extern DLLEXPORT void pfGetLModelAmbient(const pfLightModel* _lmodel, float* _r, float* _g, float* _b);
extern DLLEXPORT void pfGetLModelAtten(const pfLightModel* _lmodel, float* _a0, float* _a1, float* _a2);
extern DLLEXPORT pfType* pfGetLModelClassType(void);
extern DLLEXPORT int pfGetLModelLocal(const pfLightModel* _lmodel);
extern DLLEXPORT int pfGetLModelTwoSide(const pfLightModel* _lmodel);
extern DLLEXPORT void pfGetLODCenter(const pfLOD* _lod, PFVEC3 c);
extern DLLEXPORT pfType* pfGetLODClassType(void);
extern DLLEXPORT pfLODState* pfGetLODLODState(const pfLOD* _lod);
extern DLLEXPORT int pfGetLODLODStateIndex(const pfLOD* _lod);
extern DLLEXPORT float pfGetLODRange(const pfLOD* _lod, int index);
extern DLLEXPORT float pfGetLODStateAttr(pfLODState* _lodstate, int attr);
extern DLLEXPORT pfType* pfGetLODStateClassType(void);
extern DLLEXPORT const char* pfGetLODStateName(const pfLODState* _lodstate);
extern DLLEXPORT float pfGetLODTransition(const pfLOD* _lod, int index);
extern DLLEXPORT void pfGetLPStateBackColor(pfLPointState* _lpstate, float *r, float *g, float *b, float *a);
extern DLLEXPORT pfType* pfGetLPStateClassType(void);
extern DLLEXPORT int pfGetLPStateMode(const pfLPointState* _lpstate, int _mode);
extern DLLEXPORT void pfGetLPStateShape(const pfLPointState* _lpstate, float *_horiz, float *_vert, float *_roll, float *_falloff, float *_ambient);
extern DLLEXPORT float pfGetLPStateVal(const pfLPointState* _lpstate, int _attr);
extern DLLEXPORT pfType* pfGetLPointClassType(void);
extern DLLEXPORT pfGeoSet* pfGetLPointGSet(const pfLightPoint* _lpoint);
extern DLLEXPORT void pfGetLSourceAtten(pfLightSource* _lsource, float* _a0, float* _a1, float* _a2);
extern DLLEXPORT void* pfGetLSourceAttr(const pfLightSource* _lsource, int attr);
extern DLLEXPORT pfType* pfGetLSourceClassType(void);
extern DLLEXPORT void pfGetLSourceColor(pfLightSource* _lsource, int _which, float* _r, float* _g, float* _b);
extern DLLEXPORT int pfGetLSourceMode(const pfLightSource* _lsource, int mode);
extern DLLEXPORT void pfGetLSourcePos(pfLightSource* _lsource, float* _x, float* _y, float* _z, float* _w);
extern DLLEXPORT float pfGetLSourceVal(const pfLightSource* _lsource, int mode);
extern DLLEXPORT pfType* pfGetLayerClassType(void);
extern DLLEXPORT int pfGetLayerMode(const pfLayer* _layer);
extern DLLEXPORT void pfGetLightAtten(const pfLight* _light, float* _a0, float* _a1, float* _a2);
extern DLLEXPORT pfType* pfGetLightClassType(void);
extern DLLEXPORT void pfGetLightColor(const pfLight* _light, int _which, float* _r, float* _g, float* _b);
extern DLLEXPORT void pfGetLightPos(const pfLight* _light, float* _x, float* _y, float* _z, float* _w);
extern DLLEXPORT pfType* pfGetMemoryClassType(void);
extern DLLEXPORT pfType* pfGetMorphClassType(void);
extern DLLEXPORT void* pfGetMorphDst(const pfMorph* _morph, int index);
extern DLLEXPORT int pfGetMorphNumAttrs(const pfMorph* _morph);
extern DLLEXPORT int pfGetMorphNumSrcs(const pfMorph* _morph, int index);
extern DLLEXPORT int pfGetMorphSrc(const pfMorph* _morph, int index, int src, float **alist, ushort **ilist, int *n);
extern DLLEXPORT int pfGetMorphWeights(const pfMorph* _morph, int index, float *weights);
extern DLLEXPORT float pfGetMtlAlpha(pfMaterial* _mtl);
extern DLLEXPORT pfType* pfGetMtlClassType(void);
extern DLLEXPORT void pfGetMtlColor(pfMaterial* _mtl, int _acolor, float* _r, float* _g, float* _b);
extern DLLEXPORT int pfGetMtlColorMode(pfMaterial* _mtl, int _side);
extern DLLEXPORT float pfGetMtlShininess(pfMaterial* _mtl);
extern DLLEXPORT int pfGetMtlSide(pfMaterial* _mtl);
extern DLLEXPORT int pfGetNamedUserDataSlot(const char *_name);
extern DLLEXPORT unsigned int pfGetNodeTravMask(const pfNode* _node, int which);
extern DLLEXPORT int pfGetNumNamedUserDataSlots(void);
extern DLLEXPORT int pfGetNumStrings(const pfText* _text);
extern DLLEXPORT int pfGetNumUserData(pfObject* _obj);
extern DLLEXPORT pfType* pfGetObjectClassType(void);
extern DLLEXPORT void* pfGetPartAttr(pfPartition* _part, int which);
extern DLLEXPORT pfType* pfGetPartClassType(void);
extern DLLEXPORT float pfGetPartVal(pfPartition* _part, int which);
extern DLLEXPORT int pfGetQueueArrayLen(pfQueue* _queue);
extern DLLEXPORT void pfGetRasterFunc(pfLPointState* _lpstate, pfRasterFuncType *_rasterCallback, void **_data);
extern DLLEXPORT int pfGetRef(const void* _mem);
extern DLLEXPORT pfType* pfGetSceneClassType(void);
extern DLLEXPORT pfGeoState* pfGetSceneGState(const pfScene* _scene);
extern DLLEXPORT int pfGetSceneGStateIndex(const pfScene* _scene);
extern DLLEXPORT pfType* pfGetSeqClassType(void);
extern DLLEXPORT void pfGetSeqDuration(const pfSequence* _seq, float *sp, int *nRep);
extern DLLEXPORT void pfGetSeqInterval(const pfSequence* _seq, int *imode, int *beg, int *e);
extern DLLEXPORT int pfGetSeqMode(const pfSequence* _seq);
extern DLLEXPORT double pfGetSeqTime(const pfSequence* _seq, int index);
extern DLLEXPORT size_t pfGetSize(void *data);
extern DLLEXPORT void pfGetSpotLSourceCone(pfLightSource* _lsource, float* _f1, float* _f2);
extern DLLEXPORT void pfGetSpotLSourceDir(pfLightSource* _lsource, float* _x, float* _y, float* _z);
extern DLLEXPORT void pfGetSpotLightCone(const pfLight* _light, float* _f1, float* _f2);
extern DLLEXPORT void pfGetSpotLightDir(const pfLight* _light, float* _x, float* _y, float* _z);
extern DLLEXPORT pfString* pfGetString(const pfText* _text, int i);
extern DLLEXPORT pfType* pfGetStringClassType(void);
extern DLLEXPORT void pfGetStringColor(const pfString* _string, float *r, float *g, float *b, float *a);
extern DLLEXPORT pfFont* pfGetStringFont(const pfString* _string);
extern DLLEXPORT pfGeoState* pfGetStringGState(const pfString* _string);
extern DLLEXPORT uint pfGetStringIsectMask(const pfString* _string);
extern DLLEXPORT void pfGetStringMat(const pfString* _string, PFMATRIX _mat);
extern DLLEXPORT int pfGetStringMode(const pfString* _string, int _mode);
extern DLLEXPORT void pfGetStringSpacingScale(const pfString* _string, float *sx, float *sy, float *sz);
extern DLLEXPORT const char* pfGetStringString(const pfString* _string);
extern DLLEXPORT pfFlux* pfGetSwitchValFlux(const pfSwitch* _switch);
extern DLLEXPORT void pfGetTEnvBlendColor(pfTexEnv* _tenv, float* _r, float* _g, float* _b, float* _a);
extern DLLEXPORT pfType* pfGetTEnvClassType(void);
extern DLLEXPORT int pfGetTEnvComponent(const pfTexEnv* _tenv);
extern DLLEXPORT int pfGetTEnvMode(const pfTexEnv* _tenv);
extern DLLEXPORT pfType* pfGetTGenClassType(void);
extern DLLEXPORT int pfGetTGenMode(const pfTexGen* _tgen, int _texCoord);
extern DLLEXPORT void pfGetTGenPlane(pfTexGen* _tgen, int _texCoord, float* _x, float* _y, float* _z, float* _d);
extern DLLEXPORT void pfGetTLODBias(pfTexLOD* _tlod, float *_biasS, float *_biasT, float *_biasR);
extern DLLEXPORT void pfGetTLODRange(pfTexLOD* _tlod, float *_min, float *_max);
extern DLLEXPORT int pfGetTexAnisotropy(const pfTexture* _tex);
extern DLLEXPORT void pfGetTexBorderColor(pfTexture* _tex, pfVec4 *_clr);
extern DLLEXPORT int pfGetTexBorderType(pfTexture* _tex);
extern DLLEXPORT pfType* pfGetTexClassType(void);
extern DLLEXPORT void pfGetTexDetail(const pfTexture* _tex, int *_l, pfTexture **_detail);
extern DLLEXPORT pfTexture* pfGetTexDetailTex(const pfTexture* _tex);
extern DLLEXPORT int pfGetTexFilter(const pfTexture* _tex, int _filt);
extern DLLEXPORT int pfGetTexFormat(const pfTexture* _tex, int _format);
extern DLLEXPORT float pfGetTexFrame(const pfTexture* _tex);
extern DLLEXPORT pfTexture* pfGetTexLevel(pfTexture* _tex, int _level);
extern DLLEXPORT pfList* pfGetTexList(const pfTexture* _tex);
extern DLLEXPORT unsigned int* pfGetTexLoadImage(const pfTexture* _tex);
extern DLLEXPORT int pfGetTexLoadMode(const pfTexture* _tex, int _mode);
extern DLLEXPORT void pfGetTexLoadOrigin(pfTexture* _tex, int _which, int *_xo, int *_yo);
extern DLLEXPORT void pfGetTexLoadSize(const pfTexture* _tex, int *_xs, int *_ys);
extern DLLEXPORT const char* pfGetTexName(const pfTexture* _tex);
extern DLLEXPORT int pfGetTexRepeat(const pfTexture* _tex, int _wrap);
extern DLLEXPORT void pfGetTexSpline(const pfTexture* _tex, int _type, pfVec2 *_pts, float *_clamp);
extern DLLEXPORT pfType* pfGetTextClassType(void);
extern DLLEXPORT pfType* pfGetType(const void *data);
extern DLLEXPORT void* pfGetUserData(pfObject* _obj);
extern DLLEXPORT void* pfGetUserDataSlot(pfObject* _obj, int _slot);
extern DLLEXPORT const char* pfGetUserDataSlotName(int _slot);
extern DLLEXPORT void pfHlightAlpha(pfHighlight* _hlight, float _a);
extern DLLEXPORT void pfHlightFillPat(pfHighlight* _hlight, int _which, unsigned int *fillPat );
extern DLLEXPORT void pfHlightGState(pfHighlight* _hlight, pfGeoState *_gstate);
extern DLLEXPORT void pfHlightGStateIndex(pfHighlight* _hlight, int _id);
extern DLLEXPORT void pfHlightLinePat(pfHighlight* _hlight, int _which, unsigned short _pat);
extern DLLEXPORT void pfHlightNormalLength(pfHighlight* _hlight, float _len, float _bboxScale);
extern DLLEXPORT void pfHlightTEnv(pfHighlight* _hlight, pfTexEnv *_tev);
extern DLLEXPORT void pfHlightTGen(pfHighlight* _hlight, pfTexGen *_tgen);
extern DLLEXPORT void pfHlightTex(pfHighlight* _hlight, pfTexture *_tex);
extern DLLEXPORT void pfIBRnodeAngles(pfIBRnode* _ibrnode, int i, float horAngle, float verAngle);
extern DLLEXPORT void pfIBRnodeFlags(pfIBRnode* _ibrnode, int which, int value);
extern DLLEXPORT void pfIBRnodeIBRtexture(pfIBRnode* _ibrnode, pfIBRtexture *tex);
extern DLLEXPORT void pfIBRnodeProxyTexCoords(pfIBRnode* _ibrnode, pfVec2 ***texCoords);
extern DLLEXPORT void pfIBRtextureDirection(pfIBRtexture* _ibrtexture, float dir);
extern DLLEXPORT void pfIBRtextureFlags(pfIBRtexture* _ibrtexture, int which, int value);
extern DLLEXPORT void pfIBRtextureIBRTexture(pfIBRtexture* _ibrtexture, pfTexture **_textures, int _numTex);
extern DLLEXPORT void pfIBRtextureIBRdirections(pfIBRtexture* _ibrtexture, pfVec3 *directions, int numDirs);
extern DLLEXPORT void pfImageCacheFileStreamServer(pfImageCache* _imagecache, int _dim, int _which, const char *_device);
extern DLLEXPORT void pfImageCacheImageSize(pfImageCache* _imagecache, int _sizeS, int _sizeT, int _sizeR);
extern DLLEXPORT void pfImageCacheMaster(pfImageCache* _imagecache, pfImageCache *_master);
extern DLLEXPORT void pfImageCacheMemRegionOrg(pfImageCache* _imagecache, int _tileS, int _tileT, int _tileR);
extern DLLEXPORT void pfImageCacheMemRegionSize(pfImageCache* _imagecache, int _tileS, int _tileT, int _tileR);
extern DLLEXPORT void pfImageCacheMode(pfImageCache* _imagecache, int _mode, int _val);
extern DLLEXPORT void pfImageCacheName(pfImageCache* _imagecache, const char *_name);
extern DLLEXPORT void pfImageCacheProtoTile(pfImageCache* _imagecache, pfImageTile *tile);
extern DLLEXPORT void pfImageCacheReadQueueFunc(pfImageCache* _imagecache, pfImageCacheReadQueueFuncType _func);
extern DLLEXPORT void pfImageCacheStreamServerQueue(pfImageCache* _imagecache, int _dim, int _which, pfQueue *_q);
extern DLLEXPORT void pfImageCacheTex(pfImageCache* _imagecache, void *_dst, int _lvl, int _type);
extern DLLEXPORT void pfImageCacheTexRegionOrg(pfImageCache* _imagecache, int _originS, int _originT, int _originR);
extern DLLEXPORT void pfImageCacheTexRegionSize(pfImageCache* _imagecache, int _sizeS, int _sizeT, int _sizeR);
extern DLLEXPORT void pfImageCacheTexSize(pfImageCache* _imagecache, int _s, int _t, int _r);
extern DLLEXPORT void pfImageCacheTileFileNameFormat(pfImageCache* _imagecache, const char *_fmtString, int _nArgs, int *_argList);
extern DLLEXPORT void pfImageCacheTileFileNameFunc(pfImageCache* _imagecache, pfTileFileNameFuncType _func);
extern DLLEXPORT void pfImageTileDefaultTile(pfImageTile* _imagetile, pfImageTile *_default);
extern DLLEXPORT void pfImageTileDefaultTileMode(pfImageTile* _imagetile, int _useDefault);
extern DLLEXPORT void pfImageTileFileImageFormat(pfImageTile* _imagetile, int _fileFmt);
extern DLLEXPORT void pfImageTileFileImageType(pfImageTile* _imagetile, int _fileType);
extern DLLEXPORT void pfImageTileFileName(pfImageTile* _imagetile, const char *_fname);
extern DLLEXPORT void pfImageTileFileTile(pfImageTile* _imagetile, int _tileS, int _tileT, int _tileR);
extern DLLEXPORT void pfImageTileHeaderOffset(pfImageTile* _imagetile, int hdr);
extern DLLEXPORT void pfImageTileMemImageFormat(pfImageTile* _imagetile, int _format);
extern DLLEXPORT void pfImageTileMemImageType(pfImageTile* _imagetile, int _type);
extern DLLEXPORT void pfImageTileMemInfo(pfImageTile* _imagetile, int _psize, int _lock);
extern DLLEXPORT void pfImageTileName(pfImageTile* _imagetile, const char *_fname);
extern DLLEXPORT void pfImageTileNumFileTiles(pfImageTile* _imagetile, int _nTilesS, int _nTilesT, int _nTilesR);
extern DLLEXPORT void pfImageTileOrigin(pfImageTile* _imagetile, int _s, int _t, int _r);
extern DLLEXPORT void pfImageTilePriority(pfImageTile* _imagetile, int priority);
extern DLLEXPORT void pfImageTileReadFunc(pfImageTile* _imagetile, pfReadImageTileFuncType _func);
extern DLLEXPORT void pfImageTileReadQueue(pfImageTile* _imagetile, pfQueue *q);
extern DLLEXPORT void pfImageTileSize(pfImageTile* _imagetile, int _w, int _h, int _d);
extern DLLEXPORT int pfIsConfiged(void);
extern DLLEXPORT int pfIsDerivedFrom(pfType* _type, pfType *ancestor);
extern DLLEXPORT int pfIsLSourceOn(pfLightSource* _lsource);
extern DLLEXPORT int pfIsLightOn(pfLight* _light);
extern DLLEXPORT void pfLModelAtten(pfLightModel* _lmodel, float _a0, float _a1, float _a2);
extern DLLEXPORT void pfLModelTwoSide(pfLightModel* _lmodel, int _t);
extern DLLEXPORT void pfLODCenter(pfLOD* _lod, PFVEC3 c);
extern DLLEXPORT void pfLODLODState(pfLOD* _lod, pfLODState *ls);
extern DLLEXPORT void pfLODLODStateIndex(pfLOD* _lod, int index);
extern DLLEXPORT void pfLODStateAttr(pfLODState* _lodstate, int attr, float val);
extern DLLEXPORT int pfLODStateName(pfLODState* _lodstate, const char *name);
extern DLLEXPORT void pfLODTransition(pfLOD* _lod, int index, float delta);
extern DLLEXPORT void pfLPStateBackColor(pfLPointState* _lpstate, float r, float g, float b, float a);
extern DLLEXPORT void pfLPStateMode(pfLPointState* _lpstate, int _mode, int _val);
extern DLLEXPORT void pfLPStateShape(pfLPointState* _lpstate, float _horiz, float _vert, float _roll, float _falloff, float _ambient);
extern DLLEXPORT void pfLPStateVal(pfLPointState* _lpstate, int _attr, float _val);
extern DLLEXPORT void pfLSourceAtten(pfLightSource* _lsource, float _a0, float _a1, float _a2);
extern DLLEXPORT void pfLSourceAttr(pfLightSource* _lsource, int attr, void *obj);
extern DLLEXPORT void pfLSourceMode(pfLightSource* _lsource, int mode, int val);
extern DLLEXPORT void pfLSourceOff(pfLightSource* _lsource);
extern DLLEXPORT void pfLSourceOn(pfLightSource* _lsource);
extern DLLEXPORT void pfLSourceVal(pfLightSource* _lsource, int mode, float val);
extern DLLEXPORT void pfLayerMode(pfLayer* _layer, int mode);
extern DLLEXPORT void pfLightAtten(pfLight* _light, float _a0, float _a1, float _a2);
extern DLLEXPORT int pfMorphAttr(pfMorph* _morph, int index, int attr, int nelts, void *dst, int nsrcs, float *alist[], ushort *ilist[], int n[]);
extern DLLEXPORT int pfMorphWeights(pfMorph* _morph, int index, float *weights);
extern DLLEXPORT void pfMtlAlpha(pfMaterial* _mtl, float _alpha);
extern DLLEXPORT void pfMtlShininess(pfMaterial* _mtl, float _shininess);
extern DLLEXPORT void pfMtlSide(pfMaterial* _mtl, int _side);
extern DLLEXPORT pfASD* pfNewASD(void);
extern DLLEXPORT pfBillboard* pfNewBboard(void);
extern DLLEXPORT pfCycleBuffer* pfNewCBuffer(size_t nbytes, void *arena);
extern DLLEXPORT pfClipTexture* pfNewClipTexture(void *arena);
extern DLLEXPORT pfColortable* pfNewCtab(int _size, void *arena);
extern DLLEXPORT pfDoubleDCS* pfNewDoubleDCS(void);
extern DLLEXPORT pfDoubleFCS* pfNewDoubleFCS(pfFlux *_flux);
extern DLLEXPORT pfDoubleSCS* pfNewDoubleSCS(PFMATRIX4D m);
extern DLLEXPORT pfEngine* pfNewEngine(int _function, void *arena);
extern DLLEXPORT pfFCS* pfNewFCS(pfFlux *_flux);
extern DLLEXPORT pfFlux* pfNewFlux(size_t nbytes, int _numBuffers, void *arena);
extern DLLEXPORT pfFont* pfNewFont(void *arena);
extern DLLEXPORT pfIBRnode* pfNewIBRnode(void);
extern DLLEXPORT pfIBRtexture* pfNewIBRtexture(void *arena);
extern DLLEXPORT pfImageCache* pfNewImageCache(void *arena);
extern DLLEXPORT pfImageTile* pfNewImageTile(void *arena);
extern DLLEXPORT pfLODState* pfNewLODState(void);
extern DLLEXPORT pfLPointState* pfNewLPState(void *arena);
extern DLLEXPORT pfLayer* pfNewLayer(void);
extern DLLEXPORT pfMorph* pfNewMorph(void);
extern DLLEXPORT pfQueue* pfNewQueue(int _eltSize, int _nElts, void *arena);
extern DLLEXPORT pfSequence* pfNewSeq(void);
extern DLLEXPORT pfTexGen* pfNewTGen(void *arena);
extern DLLEXPORT pfTexLOD* pfNewTLOD(void *arena);
extern DLLEXPORT void pfRasterFunc(pfLPointState* _lpstate, pfRasterFuncType _rasterCallback, void *_data);
extern DLLEXPORT void* pfRealloc(void *data, size_t nbytes);
extern DLLEXPORT int pfRef(void* _mem);
extern DLLEXPORT int pfSaveTexFile(pfTexture* _tex, const char* _fname);
extern DLLEXPORT void pfSceneGStateIndex(pfScene* _scene, int gs);
extern DLLEXPORT void pfSeqDuration(pfSequence* _seq, float sp, int nRep);
extern DLLEXPORT void pfSeqInterval(pfSequence* _seq, int imode, int beg, int e);
extern DLLEXPORT void pfSeqMode(pfSequence* _seq, int m);
extern DLLEXPORT void pfSeqTime(pfSequence* _seq, int index, double time);
extern DLLEXPORT void pfSpotLSourceCone(pfLightSource* _lsource, float _f1, float _f2);
extern DLLEXPORT void pfSpotLSourceDir(pfLightSource* _lsource, float _x, float _y, float _z);
extern DLLEXPORT void pfSpotLightCone(pfLight* _light, float _f1, float _f2);
extern DLLEXPORT void pfSpotLightDir(pfLight* _light, float _x, float _y, float _z);
extern DLLEXPORT void pfStringBBox(pfString* _string, const pfBox* newbox);
extern DLLEXPORT void pfStringGState(pfString* _string, pfGeoState *gs);
extern DLLEXPORT void pfStringIsectMask(pfString* _string, uint _mask, int _setMode, int _bitOp);
extern DLLEXPORT void pfStringSpacingScale(pfString* _string, float sx, float sy, float sz);
extern DLLEXPORT int pfSwitchVal(pfSwitch* _switch, float val);
extern DLLEXPORT int pfSwitchValFlux(pfSwitch* _switch, pfFlux *_valFlux);
extern DLLEXPORT void pfTEnvComponent(pfTexEnv* _tenv, int _comp);
extern DLLEXPORT void pfTGenMode(pfTexGen* _tgen, int _texCoord, int _mode);
extern DLLEXPORT void pfTGenPlane(pfTexGen* _tgen, int _texCoord, float _x, float _y, float _z, float _d);
extern DLLEXPORT void pfTLODBias(pfTexLOD* _tlod, float _biasS, float _biasT, float _biasR);
extern DLLEXPORT void pfTLODRange(pfTexLOD* _tlod, float _min, float _max);
extern DLLEXPORT void pfTexAnisotropy(pfTexture* _tex, const int _degree);
extern void pfTexBorderColor(pfTexture* _tex, pfVec4 _clr);
extern DLLEXPORT void pfTexBorderType(pfTexture* _tex, int _type);
extern DLLEXPORT void pfTexDetail(pfTexture* _tex, int _l, pfTexture *_detail);
extern DLLEXPORT void pfTexFormat(pfTexture* _tex, int _format, int type);
extern DLLEXPORT void pfTexFrame(pfTexture* _tex, float _frame);
extern DLLEXPORT void pfTexImage(pfTexture* _tex, unsigned int* _image, int _comp, int _sx, int _sy, int _sz);
extern DLLEXPORT void pfTexLevel(pfTexture* _tex, int _level, pfTexture* _ltex);
extern DLLEXPORT void pfTexList(pfTexture* _tex, pfList *_list);
extern DLLEXPORT void pfTexLoadImage(pfTexture* _tex, unsigned int* _image);
extern DLLEXPORT void pfTexLoadMode(pfTexture* _tex, int _mode, int _val);
extern DLLEXPORT void pfTexLoadOrigin(pfTexture* _tex, int _which, int _xo, int _yo);
extern DLLEXPORT void pfTexLoadSize(pfTexture* _tex, int _xs, int _ys);
extern DLLEXPORT void pfTexName(pfTexture* _tex, const char *_name);
extern DLLEXPORT void pfTexRepeat(pfTexture* _tex, int _wrap, int _type);
extern DLLEXPORT void pfTexSpline(pfTexture* _tex, int _type, pfVec2 *_pts, float _clamp);
extern DLLEXPORT int pfUnref(void* _mem);
extern DLLEXPORT void pfUserDataSlot(pfObject* _obj, int _slot, void* data);

#ifdef __cplusplus
}
#endif
#endif
